import { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'hi' | 'mr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation data
const translations = {
  en: {
    // Navigation & Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.pricePrediction': 'Price Prediction',
    'nav.cropRecommendation': 'Crop Recommendation',
    'nav.weatherAdvice': 'Weather Advice',
    'nav.marketplace': 'Marketplace',
    'nav.produceListings': 'Produce Listings',
    'nav.community': 'Community',
    'nav.orders': 'Orders',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.diseaseDetection': 'Disease Detection',
    'nav.governmentSchemes': 'Government Schemes',
    'nav.profileSettings': 'Profile & Settings',
    'nav.sectionAiTools': 'AI Tools',
    'nav.sectionPlatform': 'Platform',
    'nav.sectionAccount': 'Account',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to KrishiSetu AI. Choose a tool to get started.',
    'dashboard.cropPricePrediction': 'Crop Price Prediction',
    'dashboard.cropPricePredictionDesc': 'Predict crop prices based on market trends',
    'dashboard.cropRecommendation': 'Crop Recommendation',
    'dashboard.cropRecommendationDesc': 'Get AI-powered crop recommendations',
    'dashboard.weatherAdvice': 'Weather & Farming Advice',
    'dashboard.weatherAdviceDesc': 'Real-time weather and farming tips',
    
    // Dashboard Details
    'dashboard.welcomeMsg': 'Welcome to KrishiSetu AI.',
    'dashboard.greetingMorning': 'Good morning',
    'dashboard.greetingAfternoon': 'Good afternoon',
    'dashboard.greetingEvening': 'Good evening',
    'dashboard.assistantDesc': 'Your AI-powered farming assistant for Maharashtra. Get crop predictions, detect diseases, explore government schemes, and connect with buyers — all in one place.',
    'dashboard.predictCropPrices': 'Predict Crop Prices',
    'dashboard.checkDisease': 'Check Disease',
    'dashboard.diseaseDetection': 'Disease Detection',
    'dashboard.diseaseDetectionDesc': 'Upload a photo of your crop — get instant disease diagnosis + AI treatment plan.',
    'dashboard.governmentSchemes': 'Government Schemes',
    'dashboard.governmentSchemesDesc': 'Browse loan waivers, subsidies and insurance schemes for Maharashtra farmers.',
    'dashboard.buyerMarketplace': 'Buyer Marketplace',
    'dashboard.buyerMarketplaceDesc': 'Connect with verified buyers and retailers across Maharashtra on the map.',
    'dashboard.communityHub': 'Community Hub',
    'dashboard.communityHubDesc': 'Chat with farmers, share insights, and grow together.',
    'dashboard.myOrders': 'My Orders',
    'dashboard.myOrdersDesc': 'Track your active orders and manage deliveries.',
    'dashboard.allFeatures': 'All Features',
    'dashboard.modulesAvailable': '8 modules available',
    'dashboard.open': 'Open',
    'dashboard.farmingTips': 'Farming Tips & Reminders',
    'dashboard.quickAccess': 'Quick Access',
    
    // Stats
    'stat.cropsSupported': 'Crops Supported',
    'stat.cropsSub': 'Onion, Wheat, Rice, Tomato, Potato',
    'stat.govtSchemes': 'Govt Schemes',
    'stat.schemesSub': 'Active schemes available',
    'stat.maharashtraMandis': 'Maharashtra Mandis',
    'stat.mandisSub': 'Markets tracked',
    'stat.aiModels': 'AI Models',
    'stat.modelsSub': 'Price, Disease & Weather',
    
    // Tips
    'tip.1': 'Kharif season starts June–July. Start planning water management early.',
    'tip.2': 'Upload crop images regularly to detect diseases before they spread.',
    'tip.3': 'Check 4-day price predictions before selling your produce at mandi.',
    'tip.4': 'Pradhan Mantri Fasal Bima Yojana deadline — enroll before planting.',
    
    // Badges & Labels
    'badge.aiPowered': 'AI Powered',
    'badge.smart': 'Smart',
    'badge.live': 'Live',
    'badge.geminiAi': 'Gemini AI',
    'badge.activeSchemes': '8 Active Schemes',
    'badge.liveMap': 'Live Map',
    'badge.communities': '{count} Communities',
    'badge.track': 'Track',
    'label.produceListings': 'Produce Listings',
    'label.communityHub': 'Community Hub',
    'label.profileSettings': 'Profile Settings',
    'label.appSettings': 'App Settings',
    
    // Marketplace
    'marketplace.title': 'Buyer Network',
    'marketplace.subtitle': 'Locate verified wholesale buyers and exporters for your produce directly on the map.',
    'marketplace.tabMap': 'Buyer Map',
    'marketplace.tabLive': 'Live Market & Buyers',
    'marketplace.sellingCrop': 'Selling Crop:',
    'marketplace.wheat': 'Wheat (Sharbati)',
    'marketplace.rice': 'Rice',
    'marketplace.onion': 'Onion',
    'marketplace.tomato': 'Tomato',
    'marketplace.potato': 'Potato',
    'marketplace.nearbyRetailers': 'Nearby Retailers',
    'marketplace.sortShortest': 'Shortest...',
    'marketplace.sortProfit': 'Highest Profit',
    'marketplace.sortRating': 'Best Rating',
    'marketplace.loadingBuyers': 'Loading buyers...',
    'marketplace.noBuyers': 'No buyers found',
    'marketplace.aiRecommended': 'AI Recommended',
    'marketplace.offeredPrice': 'Offered Price',
    'marketplace.transport': 'Transport',
    'marketplace.netProfit': 'Net Profit',
    'marketplace.getDirections': 'Get Directions',
    
    // Produce Listings
    'produceListings.title': 'Produce Listings',
    'produceListings.subtitle': 'Browse available produce from farmers in your area',
    'produceListings.listProduce': 'List Your Produce',
    'produceListings.loadingListings': 'Loading listings...',
    'produceListings.noListings': 'No produce listings yet',
    'produceListings.createFirst': 'Create First Listing',
    'produceListings.pricePer': 'Price per {unit}',
    'produceListings.availableQty': 'Available Quantity',
    'produceListings.totalValue': 'Total Value',
    'produceListings.contactSeller': 'Contact Seller',
    
    // Community
    'community.title': 'Community Hub',
    'community.subtitle': 'Connect with fellow farmers, share knowledge, and grow together. Explore a community or search for content below.',
    'community.loading': 'Loading communities...',
    'community.notFound': 'No communities found',
    'community.officialHub': 'Official Hub',
    'community.posts': '{count} Posts',
    'community.justNow': 'just now',
    'community.loadingDetail': 'Loading community...',
    'community.notFoundDetail': 'Community not found',
    'community.createPost': 'Create Post',
    'community.subscribe': 'Subscribe',
    'community.beFirst': 'Be the first to say hello to the {name} community!',
    'community.anonymous': 'Anonymous User',
    'community.messagePlaceholder': 'Message community...',
    'community.loginToJoin': 'Log in to join the conversation',
    'community.sendFailed': 'Failed to send message.',
    'community.about': 'About {name}',
    'community.created': 'Created {date}',
    'community.public': 'Public',
    'community.addGuide': 'Add a community guide',
    'community.moderators': 'Moderators',
    'community.messageMods': 'Message Mods',
    
    // Orders
    'orders.title': 'Farmer Orders Dashboard',
    'orders.subtitle': 'Manage your incoming produce shipments across {count} orders.',
    'orders.listProduce': 'List Your Produce',
    'orders.loading': 'Loading orders...',
    'orders.noOrders': 'No orders yet',
    'orders.listFirst': 'List Your First Produce',
    'orders.statusDelivered': 'Delivered',
    'orders.statusTransit': 'In Transit',
    'orders.statusOrdered': 'Ordered',
    'orders.orderNumber': 'Order #{id}',
    'orders.placedOn': 'Placed on {date}',
    'orders.buyer': 'Buyer: {name}',
    'orders.quantityLabel': 'QUANTITY',
    'orders.payoutLabel': 'TOTAL PAYOUT',
    
    // Profile
    'profile.title': 'Profile',
    'profile.subtitle': 'View and manage your public profile information.',
    'profile.loading': 'Loading profile...',
    'profile.pleaseLogin': 'Please log in to view your profile',
    'profile.recently': 'Recently',
    'profile.joined': 'Joined {date}',
    'profile.editProfile': 'Edit Profile',
    'profile.fullName': 'Full Name',
    'profile.fullNamePlaceholder': 'Your full name',
    'profile.locationLabel': 'Location',
    'profile.locationPlaceholder': 'e.g. Nashik, Maharashtra',
    'profile.bioLabel': 'Bio',
    'profile.bioPlaceholder': 'Tell others about yourself...',
    'profile.avatarLabel': 'Avatar URL',
    'profile.saving': 'Saving...',
    'profile.saveChanges': 'Save Changes',
    'profile.saveFailed': 'Failed to save profile',
    'profile.statsOrders': 'Orders',
    'profile.statsListings': 'Listings',
    'profile.statsCommunities': 'Communities',
    'profile.statsPosts': 'Posts',
    'profile.recentActivity': 'Recent Activity',
    'profile.noActivity': 'No recent activity yet.',
    'profile.activityDelivered': 'Delivered {product}',
    'profile.activityOrdered': 'Ordered {product}',
    'profile.activityUnits': '{quantity} units',
    'profile.activityPosted': 'Posted: {title}',
    'profile.activityCommPost': 'Community post',
    'profile.activityListed': 'Listed {crop}',
    'profile.activityListedDesc': '{quantity} units at ₹{price}/unit',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account settings, profile, and preferences.',
    'settings.profile': 'Profile',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.translation': 'Translation',
    'settings.myOrders': 'My Orders',
    'settings.chooseLanguage': 'Choose your preferred language.',
    'settings.updateProfile': 'Update Profile',
    'settings.profileSectionDesc': 'This is how others will see you on the site.',
    'settings.profilePicture': 'Profile Picture',
    'settings.username': 'Username',
    'settings.displayName': 'Display Name',
    'settings.defaultRegion': 'Default Region',
    'settings.account': 'Account',
    'settings.accountDesc': 'Manage your account security and identification.',
    'settings.userId': 'User ID',
    'settings.userIdCopied': 'User ID copied to clipboard!',
    'settings.emailAddress': 'Email Address',
    'settings.emailDesc': 'Your email address is {email}. This cannot be changed.',
    'settings.appearanceDesc': 'Customize the look and feel of the application.',
    'settings.appearanceSoon': 'Appearance settings coming soon...',
    'settings.notificationsDesc': 'Manage your notification preferences.',
    'settings.notificationsSoon': 'Notification settings coming soon...',
    'settings.ordersDesc': 'View and manage your order history.',
    'settings.ordersSoon': 'Order history coming soon...',
    'settings.note': 'Note:',
    'settings.translationNote': 'Language changes will be applied immediately. Some content may require a page refresh to fully update.',
    
    // TopBar
    'topbar.logout': 'Logout',
    
    // Auth
    'auth.login': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInToAccount': 'Sign in to your account',
    'auth.createAccount': 'Create Account',
    'auth.signUpToStart': 'Sign up to get started',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.enterName': 'Enter your name',
    'auth.confirmYourPassword': 'Confirm your password',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.passwordsDoNotMatch': 'Passwords do not match',
    'auth.passwordLengthError': 'Password must be at least 6 characters',
    
    // Landing Page
    'landing.navFeatures': 'Features',
    'landing.navHowItWorks': 'How It Works',
    'landing.navBenefits': 'Benefits',
    'landing.navAbout': 'About',
    'landing.signIn': 'Sign In',
    'landing.getStarted': 'Get Started',
    'landing.heroBadge': '🌾 AI-Powered Agricultural Intelligence',
    'landing.heroTitle1': 'Grow Smarter,',
    'landing.heroTitle2': 'Earn Better',
    'landing.heroDesc': 'Empower your farm with AI-driven crop recommendations, real-time market prices, and direct access to buyers. Make data-backed decisions that maximize your profits.',
    'landing.getStartedFree': 'Get Started Free',
    'landing.watchDemo': 'Watch Demo',
    'landing.noCreditCard': 'No Credit Card Required',
    'landing.freeForFarmers': 'Free for Farmers',
    'landing.aiAnalysisComplete': 'AI Analysis Complete',
    'landing.projectedProfit': 'Projected Profit Increase',
    'landing.marketPrice': 'Market Price',
    'landing.weatherPerfect': 'Perfect',
    'landing.whyChooseTitle': 'Why Farmers & Retailers Choose Us',
    'landing.whyChooseDesc': 'Real solutions that increase income, reduce risk, and connect farms directly to markets',
    'landing.benefit1Title': 'Higher Profits for Farmers',
    'landing.benefit1Desc': 'Get real-time market prices and AI recommendations to sell at the right time. Increase your income by up to 30% with data-driven decisions.',
    'landing.benefit2Title': 'Smarter Crop Decisions',
    'landing.benefit2Desc': 'AI analyzes your soil, weather, and market demand to recommend the most profitable crops for your land. Reduce crop failures and maximize yield.',
    'landing.benefit3Title': 'Direct Buyer Connection',
    'landing.benefit3Desc': 'Skip middlemen and sell directly to retailers and buyers. Keep more profit in your pocket with transparent, fair pricing.',
    'landing.benefit4Title': 'Reduced Losses & Risk',
    'landing.benefit4Desc': 'Weather alerts, disease predictions, and market insights help you avoid losses. Make informed decisions backed by AI intelligence.',
    'landing.benefit5Title': 'Reliable Sourcing for Retailers',
    'landing.benefit5Desc': 'Buyers get direct access to quality produce from verified farmers. Build long-term relationships and ensure consistent supply.',
    'landing.benefit6Title': 'No Middlemen Dependency',
    'landing.benefit6Desc': 'Take control of your sales and pricing. Connect directly with buyers and negotiate fair deals without losing margin to intermediaries.',
    'landing.featuresTitle': 'Powerful Features Built for Farmers',
    'landing.featuresDesc': 'Everything you need to make better farming decisions and grow your business',
    'landing.feature1Title': 'AI Crop Recommendation',
    'landing.feature1Desc': 'Get personalized crop suggestions based on your soil type, climate, and market demand. Plant what sells best.',
    'landing.feature2Title': 'Market Price Prediction',
    'landing.feature2Desc': 'See future price trends and current market rates. Know when to sell for maximum profit with AI-powered forecasts.',
    'landing.feature3Title': 'Weather Insights',
    'landing.feature3Desc': 'Get real-time weather updates and farming advice. Plan your activities with accurate forecasts and alerts.',
    'landing.feature4Title': 'Direct Buyer Marketplace',
    'landing.feature4Desc': 'List your produce and connect with verified buyers. Sell directly without middlemen and get fair prices.',
    'landing.howItWorksTitle': 'Simple. Smart. Profitable.',
    'landing.howItWorksDesc': 'Start making better farming decisions in just 3 easy steps',
    'landing.step1Title': 'Enter Farm Details',
    'landing.step1Desc': 'Tell us about your land size, soil type, location, and what you want to grow. Takes less than 2 minutes.',
    'landing.step2Title': 'AI Analyzes Data',
    'landing.step2Desc': 'Our AI studies weather patterns, market prices, soil conditions, and demand to find the best opportunities for you.',
    'landing.step3Title': 'Get Results & Connect',
    'landing.step3Desc': 'Receive crop recommendations, price predictions, and connect with buyers ready to purchase your produce at fair prices.',
    'landing.startJourney': 'Start Your Journey',
    'landing.previewTitle': 'See KrishiSetu-AI in Action',
    'landing.previewDesc': 'A complete platform designed for modern farmers and smart retailers',
    'landing.farmerDashboard': 'Farmer Dashboard',
    'landing.cropRecs': 'Crop Recommendations',
    'landing.basedOnSoil': 'Based on your soil & market',
    'landing.buyerDashboard': 'Buyer Dashboard',
    'landing.availableProduce': 'Available Produce',
    'landing.fromVerified': 'From verified farmers',
    'landing.realTimeMarket': 'Real-time',
    'landing.marketData': 'Market Data',
    'landing.aiRecsLarge': 'AI-Powered',
    'landing.aiRecsDesc': 'Recommendations',
    'landing.directAccessLarge': 'Direct',
    'landing.directAccessDesc': 'Buyer Access',
    'landing.supportLarge': '24/7',
    'landing.supportDesc': 'Support',
    'landing.impactTitle': 'Real Impact. Real Results.',
    'landing.impactDesc': 'Transforming agriculture through technology and empowering farming communities',
    'landing.incomeIncrease': 'Average Income Increase',
    'landing.lossReduction': 'Reduction in Crop Losses',
    'landing.transparentPricing': 'Transparent Pricing',
    'landing.noMiddlemen': 'Middlemen Required',
    'landing.verifiedFarmersTitle': 'Verified Farmers',
    'landing.verifiedFarmersDesc': 'All farmers are verified to ensure quality and authenticity for buyers',
    'landing.secureTransTitle': 'Secure Transactions',
    'landing.secureTransDesc': 'Safe and secure payment processing with buyer protection',
    'landing.expertSupportTitle': 'Expert Support',
    'landing.expertSupportDesc': 'Agricultural experts available to help you succeed',
    'landing.readyToTransform': 'Ready to Transform Your Farming?',
    'landing.ctaDesc': 'Join thousands of farmers who are already earning more, reducing losses, and connecting directly with buyers. Start your journey to smarter, more profitable farming today.',
    'landing.scheduleDemo': 'Schedule a Demo',
    'landing.setupTime': 'Setup in 2 Minutes',
    'landing.footerDesc': 'Empowering farmers with AI-driven insights and connecting them directly to markets. Building a smarter, more profitable future for agriculture.',
    'landing.builtFor': 'Built for National Hackathon 2024',
    'landing.quickLinks': 'Quick Links',
    'landing.privacyPolicy': 'Privacy Policy',
    'landing.termsOfService': 'Terms of Service',
    'landing.support': 'Support',
    'landing.allRightsReserved': 'All rights reserved.',

    
    // Crop Recommendation
    'cropRecommendation.title': 'Crop Recommendation',
    'cropRecommendation.subtitle': 'Get AI-powered crop recommendations based on your location, soil type, and farming conditions.',
    'cropRecommendation.getRecommendations': 'Get Crop Recommendations',
    'cropRecommendation.newRecommendation': 'Get New Recommendation',
    'cropRecommendation.locationInfo': 'Location Information',
    'cropRecommendation.useCurrentLocation': 'Use Current Location',
    'cropRecommendation.enterManually': 'Enter Manually',
    'cropRecommendation.getCurrentLocation': 'Get Current Location',
    'cropRecommendation.gettingLocation': 'Getting Location...',
    'cropRecommendation.farmDetails': 'Farm Details',
    'cropRecommendation.soilType': 'Soil Type',
    'cropRecommendation.selectSoilType': 'Select Soil Type',
    'cropRecommendation.season': 'Season',
    'cropRecommendation.selectSeason': 'Select Season',
    'cropRecommendation.farmSize': 'Farm Size (acres)',
    'cropRecommendation.enterFarmSize': 'Enter farm size',
    'cropRecommendation.budget': 'Budget (₹)',
    'cropRecommendation.enterBudget': 'Enter budget',
    'cropRecommendation.waterAvailability': 'Water Availability',
    'cropRecommendation.selectWaterAvailability': 'Select Water Availability',
    'cropRecommendation.farmingExperience': 'Farming Experience',
    'cropRecommendation.selectExperience': 'Select Experience Level',
    'cropRecommendation.previousCrops': 'Previous Crops (Select all that apply)',
    'cropRecommendation.gettingRecommendations': 'Getting Recommendations...',
    'cropRecommendation.recommendedCrops': 'Recommended Crops',
    'cropRecommendation.suitability': 'Suitability',
    'cropRecommendation.expectedYield': 'Expected Yield',
    'cropRecommendation.whySuitable': 'Why this crop is suitable:',
    'cropRecommendation.bestCropToGrow': 'Best Crop to Grow',
    'cropRecommendation.topRecommendation': 'Our top recommendation for your farm',
    'cropRecommendation.saveResults': 'Save Results',
    'cropRecommendation.demoModeActive': 'Demo Mode Active',
    'cropRecommendation.errorGettingRecommendations': 'Error getting recommendations',
    
    // Risk Levels
    'risk.low': 'Low Risk',
    'risk.medium': 'Medium Risk',
    'risk.high': 'High Risk',
    
    // Languages
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.marathi': 'मराठी (Marathi)',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.state': 'State',
    'common.district': 'District',
    'common.location': 'Location',
    'common.coordinates': 'Coordinates',
    
    // Weather Advice
    'weather.title': 'Weather & Farming Advice',
    'weather.subtitle': 'Get AI-powered weather forecasts and actionable farming tips for your location.',
    'weather.getAdvice': 'Get Weather Advice',
    'weather.newSearch': 'New Search',
    'weather.currentWeather': 'Current Weather',
    'weather.forecast': '3-Day Forecast',
    'weather.warnings': 'Weather Warnings',
    'weather.suitableActivities': 'Suitable Activities',
    'weather.recommendedCrops': 'Recommended Crops',
    'weather.irrigationAdvice': 'Irrigation Advice',
    'weather.pestControl': 'Pest Control',
    'weather.farmingRecommendations': 'Farming Recommendations',
    'weather.useCurrentLocation': 'Use Current Location',
    'weather.enterCityName': 'Enter City Name',
    'weather.getCurrentLocation': 'Get Current Location',
    'weather.gettingLocation': 'Getting Location...',
    'weather.cityName': 'City Name',
    'weather.enterCity': 'Enter city name (e.g., Mumbai, Delhi, Pune)',
    'weather.gettingWeatherAdvice': 'Getting Weather Advice...',
    'weather.temperature': 'Temperature',
    'weather.humidity': 'Humidity',
    'weather.windSpeed': 'Wind Speed',
    'weather.visibility': 'Visibility',
    'weather.pressure': 'Pressure',
    'weather.uvIndex': 'UV Index',
    'weather.condition': 'Condition',
    'weather.feelsLike': 'Feels like',
    'weather.today': 'Today',
    'weather.tomorrow': 'Tomorrow',
    'weather.dayAfter': 'Day After',
    'weather.highLow': 'High/Low',
    'weather.rain': 'Rain',
    'weather.needed': 'Needed',
    'weather.amount': 'Amount',
    'weather.timing': 'Timing',
    'weather.method': 'Method',
    'weather.riskLevel': 'Risk Level',
    'weather.recommendations': 'Recommendations',
    'weather.priority': 'Priority',
    'weather.high': 'HIGH',
    'weather.medium': 'MEDIUM',
    'weather.low': 'LOW',
    'weather.yes': 'Yes',
    'weather.no': 'No',
    'weather.errorGettingAdvice': 'Error getting weather advice',
    'weather.adviceIncludes': 'Weather Advice includes: Current conditions, 3-day forecast, farming recommendations, irrigation advice, pest control tips, and suitable activities.',

    // Government Schemes
    'schemes.title': 'Government Schemes for Farmers',
    'schemes.subtitle': 'Explore and apply for various government schemes available for Maharashtra farmers',
    'schemes.searchPlaceholder': 'Search schemes...',
    'schemes.filterByCategory': 'Filter by Category',
    'schemes.allSchemes': 'All Schemes',
    'schemes.loanWaiver': 'Loan Waiver',
    'schemes.subsidy': 'Subsidy',
    'schemes.insurance': 'Insurance',
    'schemes.directBenefit': 'Direct Benefit',
    'schemes.infrastructure': 'Infrastructure',
    'schemes.noSchemesFound': 'No schemes found matching your criteria',
    'schemes.keyBenefits': 'Key Benefits',
    'schemes.eligibilityCriteria': 'Eligibility Criteria',
    'schemes.howToApply': 'How to Apply',
    'schemes.budgetAllocation': 'Budget Allocation',
    'schemes.targetBeneficiaries': 'Target Beneficiaries',
    'schemes.officialWebsite': 'Official Website',
    'schemes.visit': 'Visit',
    'schemes.learnMore': 'Learn More & Apply',

    // Specific Schemes (Examples)
    'schemes.item1.name': 'Punyashlok Ahilyadevi Holkar Shetkari Karjmafi Yojana',
    'schemes.item1.desc': 'Crop loan waiver scheme for farmers with outstanding dues',
    'schemes.item2.name': 'Mukhya Mantri Baliraj Vij Yojana',
    'schemes.item2.desc': 'Free electricity for agricultural pumps',
    'schemes.item3.name': 'Cotton and Soybean Farmer Assistance Scheme',
    'schemes.item3.desc': 'Financial assistance for cotton and soybean farmers',
    'schemes.item4.name': 'Gopinath Munde Farmer Welfare Scheme',
    'schemes.item4.desc': 'Emergency financial aid for distressed farmers',
    'schemes.item5.name': 'Farmer Accident Insurance Scheme',
    'schemes.item5.desc': 'Accident insurance coverage for farmers and agricultural laborers',
    'schemes.item6.name': 'Marathwada Water Grid Project',
    'schemes.item6.desc': 'Water management and irrigation infrastructure development',
    'schemes.item7.name': 'Pradhan Mantri Fasal Bima Yojana',
    'schemes.item7.desc': 'Crop insurance scheme for protection against crop loss',
    'schemes.item8.name': 'Soil Health Card Scheme',
    'schemes.item8.desc': 'Free soil testing and nutrient management guidance',

    // Price Prediction
    'price.title': 'Crop Price Prediction',
    'price.subtitle': 'Predict the price of a crop based on region and date using our AI-powered model.',
    'price.analyzerTitle': 'Price Prediction Analyzer',
    'price.selectCrop': 'Select Crop',
    'price.selectMandi': 'Select Mandi',
    'price.predictPrices': 'Predict Prices',
    'price.loading': 'Loading predictions...',
    'price.error': 'Error fetching predictions',
    'price.fourDayForecast': '4-Day Price Forecast',
    'price.dayX': 'DAY {day}',
    'price.predictedPriceQuintal': 'Predicted Price (₹/Quintal)',
    'price.topMarketFactors': 'Top Market Factors',
    'price.aiConfidence': 'AI Confidence',
    'price.historicalBaseline': 'Historical baseline pricing for {crop}',
    'price.regionalVariations': 'Regional variations for {mandi} Mandi',
    'price.seasonalSupply': 'Standard seasonal supply patterns',
    'price.trendDisclaimer': 'Based on historical mandi price trends (2020–2025). Models update dynamically on available live data.',
    'price.historical': 'Historical',
    'price.predicted': 'Predicted',
    'price.chartTitle': 'Historical vs AI-Predicted Prices (₹/quintal)',
    'price.today': 'Today',

    // Disease Detection
    'disease.title': 'Disease Detection',
    'disease.subtitle': 'Identify crop diseases early and get treatment recommendations to protect your harvest.',
    'disease.error': 'Error detecting disease',
    'disease.failedToConnect': 'Failed to connect to the prediction server.',
    'disease.uploadTitle': 'Upload Plant Image',
    'disease.clickToUpload': 'Click to upload or drag and drop',
    'disease.imageFormats': 'PNG, JPG, GIF up to 10MB',
    'disease.clickToChange': 'Click here to change image',
    'disease.alertUpload': 'Please upload a plant image for disease detection',
    'disease.analyzing': 'Analyzing...',
    'disease.detectButton': 'Detect Disease',
    'disease.confidenceLevel': 'Confidence Level',
    'disease.symptomsTitle': 'Symptoms to Look For',
    'disease.treatmentTitle': 'Treatment Recommendations',
    'disease.preventionTitle': 'Prevention Measures',
    'disease.analyzeAnother': 'Analyze Another Plant',
    'disease.saveReport': 'Save Report',
    'disease.detectedOnPlant': 'Detected on plant: {plant}',
    'disease.label': 'Label: {label}',
    
    // Default/Fallback strings
    'disease.diagVisual': 'Diagnosis based on visual analysis',
    'disease.checkSurround': 'Check surrounding plants for similar signs',
    'disease.consultExpert': 'Consult an agricultural expert',
    'disease.reviewTreatments': 'Review specific fungicides or treatments for this disease',
    'disease.ensureRotation': 'Ensure crop rotation and proper spacing',
    'disease.avoidOverhead': 'Avoid overhead irrigation if possible',
    
    'disease.healthy.name': 'Healthy',
    'disease.healthy.symptom1': 'No visible symptoms of disease',
    'disease.healthy.symptom2': 'Plant appears healthy and vibrant',
    'disease.healthy.treatment1': 'No treatment required',
    'disease.healthy.treatment2': 'Continue regular care and monitoring',
    'disease.healthy.prevention1': 'Maintain proper watering schedule',
    'disease.healthy.prevention2': 'Ensure adequate sunlight and nutrients',
  },
  hi: {
    // Navigation & Sidebar
    'nav.dashboard': 'डैशबोर्ड',
    'nav.pricePrediction': 'मूल्य पूर्वानुमान',
    'nav.cropRecommendation': 'फसल सिफारिश',
    'nav.weatherAdvice': 'मौसम सलाह',
    'nav.marketplace': 'बाज़ार',
    'nav.produceListings': 'उत्पाद सूची',
    'nav.community': 'समुदाय',
    'nav.orders': 'ऑर्डर',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.settings': 'सेटिंग्स',
    'nav.diseaseDetection': 'रोग पहचान',
    'nav.governmentSchemes': 'सरकारी योजनाएं',
    'nav.profileSettings': 'प्रोफ़ाइल और सेटिंग्स',
    'nav.sectionAiTools': 'AI उपकरण',
    'nav.sectionPlatform': 'प्लैटफ़ॉर्म',
    'nav.sectionAccount': 'खाता',
    
    // Dashboard Details
    'dashboard.welcomeMsg': 'कृषिसेतु AI में आपका स्वागत है।',
    'dashboard.greetingMorning': 'सुप्रभात',
    'dashboard.greetingAfternoon': 'नमस्कार',
    'dashboard.greetingEvening': 'शुभ संध्या',
    'dashboard.assistantDesc': 'महाराष्ट्र के लिए आपका AI-संचालित कृषि सहायक। फसल की कीमतों का पूर्वानुमान प्राप्त करें, बीमारियों का पता लगाएं, सरकारी योजनाओं का अन्वेषण करें, और खरीदारों से जुड़ें - सब एक जगह पर।',
    'dashboard.predictCropPrices': 'फसल की कीमतों का पूर्वानुमान लगाएं',
    'dashboard.checkDisease': 'बीमारी की जांच करें',
    'dashboard.diseaseDetection': 'रोग का पता लगाना',
    'dashboard.diseaseDetectionDesc': 'अपनी फसल की तस्वीर अपलोड करें — तत्काल रोग निदान + AI उपचार योजना प्राप्त करें।',
    'dashboard.governmentSchemes': 'सरकारी योजनाएं',
    'dashboard.governmentSchemesDesc': 'महाराष्ट्र के किसानों के लिए ऋण माफी, सब्सिडी और बीमा योजनाएं ब्राउज़ करें।',
    'dashboard.buyerMarketplace': 'खरीदार बाज़ार',
    'dashboard.buyerMarketplaceDesc': 'मानचित्र पर पूरे महाराष्ट्र में सत्यापित खरीदारों और खुदरा विक्रेताओं से जुड़ें।',
    'dashboard.communityHub': 'सामुदायिक केंद्र',
    'dashboard.communityHubDesc': 'किसानों के साथ बातचीत करें, विचार साझा करें, और एक साथ बढ़ें।',
    'dashboard.myOrders': 'मेरे ऑर्डर',
    'dashboard.myOrdersDesc': 'अपने सक्रिय ऑर्डर ट्रैक करें और डिलीवरी प्रबंधित करें।',
    'dashboard.allFeatures': 'सभी सुविधाएँ',
    'dashboard.modulesAvailable': '8 मॉड्यूल उपलब्ध',
    'dashboard.open': 'खोलें',
    'dashboard.farmingTips': 'कृषि सुझाव और अनुस्मारक',
    'dashboard.quickAccess': 'त्वरित पहुँच',
    
    // Stats
    'stat.cropsSupported': 'समर्थित फसलें',
    'stat.cropsSub': 'प्याज, गेहूं, चावल, टमाटर, आलू',
    'stat.govtSchemes': 'सरकारी योजनाएं',
    'stat.schemesSub': 'सक्रिय योजनाएं उपलब्ध',
    'stat.maharashtraMandis': 'महाराष्ट्र की मंडियां',
    'stat.mandisSub': 'बाजारों पर नज़र',
    'stat.aiModels': 'AI मॉडल',
    'stat.modelsSub': 'मूल्य, रोग और मौसम',
    
    // Tips
    'tip.1': 'खरीफ का मौसम जून-जुलाई से शुरू होता है। जल प्रबंधन की योजना जल्द शुरू करें।',
    'tip.2': 'फसलों में फैलने से पहले बीमारियों का पता लगाने के लिए नियमित रूप से चित्र अपलोड करें।',
    'tip.3': 'मंडी में अपनी उपज बेचने से पहले 4-दिवसीय मूल्य पूर्वानुमान देखें।',
    'tip.4': 'प्रधानमंत्री फसल बीमा योजना की समय सीमा — बुवाई से पहले नामांकन करें।',
    
    // Badges & Labels
    'badge.aiPowered': 'AI संचालित',
    'badge.smart': 'स्मार्ट',
    'badge.live': 'लाइव',
    'badge.geminiAi': 'Gemini AI',
    'badge.activeSchemes': '8 सक्रिय योजनाएं',
    'badge.liveMap': 'लाइव मानचित्र',
    'badge.communities': '{count} समुदाय',
    'badge.track': 'ट्रैक करें',
    'label.produceListings': 'उत्पाद सूची',
    'label.communityHub': 'सामुदायिक केंद्र',
    'label.profileSettings': 'प्रोफ़ाइल सेटिंग्स',
    'label.appSettings': 'ऐप सेटिंग्स',
    
    // Marketplace
    'marketplace.title': 'खरीदार नेटवर्क',
    'marketplace.subtitle': 'मानचित्र पर सीधे अपनी उपज के लिए सत्यापित थोक खरीदारों और निर्यातकों का पता लगाएं।',
    'marketplace.tabMap': 'खरीदार मानचित्र',
    'marketplace.tabLive': 'लाइव बाज़ार और खरीदार',
    'marketplace.sellingCrop': 'फसल बेचना:',
    'marketplace.wheat': 'गेहूं (शरबती)',
    'marketplace.rice': 'चावल',
    'marketplace.onion': 'प्याज',
    'marketplace.tomato': 'टमाटर',
    'marketplace.potato': 'आलू',
    'marketplace.nearbyRetailers': 'नज़दीकी खुदरा विक्रेता',
    'marketplace.sortShortest': 'सबसे छोटा...',
    'marketplace.sortProfit': 'सबसे अधिक लाभ',
    'marketplace.sortRating': 'सर्वश्रेष्ठ रेटिंग',
    'marketplace.loadingBuyers': 'खरीदार लोड हो रहे हैं...',
    'marketplace.noBuyers': 'कोई खरीदार नहीं मिला',
    'marketplace.aiRecommended': 'AI अनुशंसित',
    'marketplace.offeredPrice': 'प्रस्तावित मूल्य',
    'marketplace.transport': 'परिवहन',
    'marketplace.netProfit': 'शुद्ध लाभ',
    'marketplace.getDirections': 'दिशा-निर्देश प्राप्त करें',
    
    // Produce Listings
    'produceListings.title': 'उत्पाद सूची',
    'produceListings.subtitle': 'अपने क्षेत्र के किसानों से उपलब्ध उपज ब्राउज़ करें',
    'produceListings.listProduce': 'अपनी उपज सूचीबद्ध करें',
    'produceListings.loadingListings': 'सूचियां लोड हो रही हैं...',
    'produceListings.noListings': 'अभी तक कोई उत्पाद सूची नहीं',
    'produceListings.createFirst': 'पहली सूची बनाएं',
    'produceListings.pricePer': 'प्रति {unit} मूल्य',
    'produceListings.availableQty': 'उपलब्ध मात्रा',
    'produceListings.totalValue': 'कुल मूल्य',
    'produceListings.contactSeller': 'विक्रेता से संपर्क करें',
    
    // Community
    'community.title': 'सामुदायिक केंद्र',
    'community.subtitle': 'साथी किसानों से जुड़ें, ज्ञान साझा करें और एक साथ बढ़ें। नीचे किसी समुदाय का अन्वेषण करें या सामग्री खोजें।',
    'community.loading': 'समुदाय लोड हो रहे हैं...',
    'community.notFound': 'कोई समुदाय नहीं मिला',
    'community.officialHub': 'आधिकारिक केंद्र',
    'community.posts': '{count} पोस्ट',
    'community.justNow': 'अभी-अभी',
    'community.loadingDetail': 'समुदाय लोड हो रहा है...',
    'community.notFoundDetail': 'समुदाय नहीं मिला',
    'community.createPost': 'पोस्ट बनाएं',
    'community.subscribe': 'सदस्यता लें',
    'community.beFirst': '{name} समुदाय को नमस्ते कहने वाले पहले व्यक्ति बनें!',
    'community.anonymous': 'अनाम उपयोगकर्ता',
    'community.messagePlaceholder': 'समुदाय को संदेश दें...',
    'community.loginToJoin': 'बातचीत में शामिल होने के लिए लॉग इन करें',
    'community.sendFailed': 'संदेश भेजने में विफल।',
    'community.about': '{name} के बारे में',
    'community.created': '{date} बनाया गया',
    'community.public': 'सार्वजनिक',
    'community.addGuide': 'एक समुदाय मार्गदर्शिका जोड़ें',
    'community.moderators': 'स modernators',
    'community.messageMods': 'मॉडरेटर्स को संदेश',
    
    // Orders
    'orders.title': 'किसान आदेश डैशबोर्ड',
    'orders.subtitle': '{count} ऑर्डर में अपने आवक उपज शिपमेंट का प्रबंधन करें।',
    'orders.listProduce': 'अपनी उपज सूचीबद्ध करें',
    'orders.loading': 'ऑर्डर लोड हो रहे हैं...',
    'orders.noOrders': 'अभी तक कोई आदेश नहीं',
    'orders.listFirst': 'अपनी पहली उपज सूचीबद्ध करें',
    'orders.statusDelivered': 'पहुंचा दिया गया',
    'orders.statusTransit': 'रास्ते में',
    'orders.statusOrdered': 'आदेश दिया',
    'orders.orderNumber': 'ऑर्डर #{id}',
    'orders.placedOn': '{date} को रखा गया',
    'orders.buyer': 'खरीदार: {name}',
    'orders.quantityLabel': 'मात्रा',
    'orders.payoutLabel': 'कुल भुगतान',
    
    // Profile
    'profile.title': 'प्रोफ़ाइल',
    'profile.subtitle': 'अपनी सार्वजनिक प्रोफ़ाइल जानकारी देखें और प्रबंधित करें।',
    'profile.loading': 'प्रोफ़ाइल लोड हो रही है...',
    'profile.pleaseLogin': 'कृपया अपनी प्रोफ़ाइल देखने के लिए लॉग इन करें',
    'profile.recently': 'हाल ही में',
    'profile.joined': 'जुड़े {date}',
    'profile.editProfile': 'प्रोफ़ाइल संपादित करें',
    'profile.fullName': 'पूरा नाम',
    'profile.fullNamePlaceholder': 'आपका पूरा नाम',
    'profile.locationLabel': 'स्थान',
    'profile.locationPlaceholder': 'उदाहरण: नासिक, महाराष्ट्र',
    'profile.bioLabel': 'बायो',
    'profile.bioPlaceholder': 'दूसरों को अपने बारे में बताएं...',
    'profile.avatarLabel': 'अवतार URL',
    'profile.saving': 'सहेजा जा रहा है...',
    'profile.saveChanges': 'परिवर्तन सहेजें',
    'profile.saveFailed': 'प्रोफ़ाइल सहेजने में विफल',
    'profile.statsOrders': 'ऑर्डर',
    'profile.statsListings': 'सूचियां',
    'profile.statsCommunities': 'समुदाय',
    'profile.statsPosts': 'पोस्ट',
    'profile.recentActivity': 'हाल की गतिविधि',
    'profile.noActivity': 'अभी तक कोई हालिया गतिविधि नहीं।',
    'profile.activityDelivered': 'वितरित {product}',
    'profile.activityOrdered': 'आदेशित {product}',
    'profile.activityUnits': '{quantity} इकाइयाँ',
    'profile.activityPosted': 'पोस्ट किया गया: {title}',
    'profile.activityCommPost': 'सामुदायिक पोस्ट',
    'profile.activityListed': 'सूचीबद्ध {crop}',
    'profile.activityListedDesc': '{quantity} इकाइयाँ ₹{price}/इकाई',
    
    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.subtitle': 'अपने खाता सेटिंग्स, प्रोफ़ाइल और प्राथमिकताओं का प्रबंधन करें।',
    'settings.profile': 'प्रोफ़ाइल',
    'settings.appearance': 'दिखावट',
    'settings.notifications': 'सूचनाएं',
    'settings.translation': 'अनुवाद',
    'settings.myOrders': 'मेरे ऑर्डर',
    'settings.chooseLanguage': 'अपनी पसंदीदा भाषा चुनें।',
    'settings.updateProfile': 'प्रोफ़ाइल अपडेट करें',
    'settings.profileSectionDesc': 'इस तरह दूसरे आपको साइट पर देखेंगे।',
    'settings.profilePicture': 'प्रोफ़ाइल चित्र',
    'settings.username': 'उपयोगकर्ता नाम',
    'settings.displayName': 'प्रदर्शन नाम',
    'settings.defaultRegion': 'डिफ़ॉल्ट क्षेत्र',
    'settings.account': 'खाता',
    'settings.accountDesc': 'अपने खाते की सुरक्षा और पहचान प्रबंधित करें।',
    'settings.userId': 'यूज़र आईडी',
    'settings.userIdCopied': 'यूज़र आईडी क्लिपबोर्ड पर कॉपी हो गई!',
    'settings.emailAddress': 'ईमेल पता',
    'settings.emailDesc': 'आपका ईमेल पता {email} है। इसे बदला नहीं जा सकता।',
    'settings.appearanceDesc': 'एप्लिकेशन के रूप और अनुभव को अनुकूलित करें।',
    'settings.appearanceSoon': 'प्रकटन सेटिंग्स जल्द ही आ रही हैं...',
    'settings.notificationsDesc': 'अपनी अधिसूचना प्राथमिकताएं प्रबंधित करें।',
    'settings.notificationsSoon': 'अधिसूचना सेटिंग्स जल्द ही आ रही हैं...',
    'settings.ordersDesc': 'अपना आदेश इतिहास देखें और प्रबंधित करें।',
    'settings.ordersSoon': 'आदेश इतिहास जल्द ही आ रहा है...',
    'settings.note': 'नोट:',
    'settings.translationNote': 'भाषा परिवर्तन तुरंत लागू किए जाएंगे। कुछ सामग्री को पूरी तरह से अपडेट करने के लिए पृष्ठ को ताज़ा करने की आवश्यकता हो सकती है।',
    
    // TopBar
    'topbar.logout': 'लॉग आउट',
    
    // Auth
    'auth.login': 'साइन इन',
    'auth.signup': 'साइन अप',
    'auth.welcomeBack': 'वापसी पर स्वागत',
    'auth.signInToAccount': 'अपने खाते में साइन इन करें',
    'auth.createAccount': 'खाता बनाएं',
    'auth.signUpToStart': 'शुरू करने के लिए साइन अप करें',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.fullName': 'पूरा नाम',
    'auth.enterEmail': 'अपना ईमेल दर्ज करें',
    'auth.enterPassword': 'अपना पासवर्ड दर्ज करें',
    'auth.enterName': 'अपना नाम दर्ज करें',
    'auth.confirmYourPassword': 'अपने पासवर्ड की पुष्टि करें',
    'auth.signingIn': 'साइन इन हो रहा है...',
    'auth.creatingAccount': 'खाता बनाया जा रहा है...',
    'auth.dontHaveAccount': 'खाता नहीं है?',
    'auth.alreadyHaveAccount': 'पहले से खाता है?',
    'auth.passwordsDoNotMatch': 'पासवर्ड मेल नहीं खाते',
    'auth.passwordLengthError': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    
    // Landing Page
    'landing.navFeatures': 'विशेषताएं',
    'landing.navHowItWorks': 'यह कैसे काम करता है',
    'landing.navBenefits': 'लाभ',
    'landing.navAbout': 'हमारे बारे में',
    'landing.signIn': 'साइन इन करें',
    'landing.getStarted': 'शुरू करें',
    'landing.heroBadge': '🌾 AI-संचालित कृषि बुद्धिमत्ता',
    'landing.heroTitle1': 'होशियारी से उगाएं,',
    'landing.heroTitle2': 'बेहतर कमाएं',
    'landing.heroDesc': 'AI-संचालित फसल सिफारिशों, वास्तविक समय की बाजार कीमतों और खरीदारों तक सीधी पहुंच के साथ अपने खेत को सशक्त बनाएं। डेटा-आधारित निर्णय लें जो आपके लाभ को अधिकतम करें।',
    'landing.getStartedFree': 'मुफ्त में शुरू करें',
    'landing.watchDemo': 'डेमो देखें',
    'landing.noCreditCard': 'किसी क्रेडिट कार्ड की आवश्यकता नहीं',
    'landing.freeForFarmers': 'किसानों के लिए मुफ्त',
    'landing.aiAnalysisComplete': 'AI विश्लेषण पूर्ण',
    'landing.projectedProfit': 'अनुमानित लाभ वृद्धि',
    'landing.marketPrice': 'बाजार मूल्य',
    'landing.weatherPerfect': 'उत्तम',
    'landing.whyChooseTitle': 'किसान और खुदरा विक्रेता हमें क्यों चुनते हैं',
    'landing.whyChooseDesc': 'वास्तविक समाधान जो आय बढ़ाते हैं, जोखिम कम करते हैं, और खेतों को सीधे बाजारों से जोड़ते हैं',
    'landing.benefit1Title': 'किसानों के लिए उच्च लाभ',
    'landing.benefit1Desc': 'सही समय पर बेचने के लिए वास्तविक समय की बाजार कीमतें और AI सिफारिशें प्राप्त करें। डेटा-संचालित निर्णयों के साथ अपनी आय में 30% तक की वृद्धि करें।',
    'landing.benefit2Title': 'स्मार्ट फसल निर्णय',
    'landing.benefit2Desc': 'AI आपकी मिट्टी, मौसम और बाजार की मांग का विश्लेषण करता है ताकि आपकी भूमि के लिए सबसे अधिक लाभदायक फसलों की सिफारिश की जा सके। फसल की विफलता कम करें और पैदावार अधिकतम करें।',
    'landing.benefit3Title': 'सीधा खरीदार संपर्क',
    'landing.benefit3Desc': 'बिचौलियों को छोड़ें और सीधे खुदरा विक्रेताओं और खरीदारों को बेचें। पारदर्शी, उचित मूल्य निर्धारण के साथ अपनी जेब में अधिक लाभ रखें।',
    'landing.benefit4Title': 'नुकसान और जोखिम में कमी',
    'landing.benefit4Desc': 'मौसम की चेतावनी, बीमारी की भविष्यवाणी और बाजार की जानकारी आपको नुकसान से बचने में मदद करती है। AI बुद्धिमत्ता द्वारा समर्थित सूचित निर्णय लें।',
    'landing.benefit5Title': 'खुदरा विक्रेताओं के लिए विश्वसनीय सोर्सिंग',
    'landing.benefit5Desc': 'खरीदारों को सत्यापित किसानों से गुणवत्तापूर्ण उपज तक सीधी पहुंच मिलती है। दीर्घकालिक संबंध बनाएं और निरंतर आपूर्ति सुनिश्चित करें।',
    'landing.benefit6Title': 'कोई बिचौलिया निर्भरता नहीं',
    'landing.benefit6Desc': 'अपनी बिक्री और मूल्य निर्धारण पर नियंत्रण रखें। खरीदारों के साथ सीधे जुड़ें और बिचौलियों को मार्जिन खोए बिना उचित सौदे तय करें।',
    'landing.featuresTitle': 'किसानों के लिए बनाई गई शक्तिशाली विशेषताएं',
    'landing.featuresDesc': 'बेहतर कृषि निर्णय लेने और अपना व्यवसाय बढ़ाने के लिए आपको जो कुछ भी चाहिए',
    'landing.feature1Title': 'AI फसल सिफारिश',
    'landing.feature1Desc': 'अपनी मिट्टी के प्रकार, जलवायु और बाजार की मांग के आधार पर व्यक्तिगत फसल सुझाव प्राप्त करें। वही उगाएं जो सबसे अच्छा बिकता है।',
    'landing.feature2Title': 'बाजार मूल्य भविष्यवाणी',
    'landing.feature2Desc': 'भविष्य के मूल्य रुझान और वर्तमान बाजार दरें देखें। AI-संचालित पूर्वानुमानों के साथ जानें कि अधिकतम लाभ के लिए कब बेचना है।',
    'landing.feature3Title': 'मौसम की जानकारी',
    'landing.feature3Desc': 'वास्तविक समय के मौसम अपडेट और कृषि सलाह प्राप्त करें। सटीक पूर्वानुमान और अलर्ट के साथ अपनी गतिविधियों की योजना बनाएं।',
    'landing.feature4Title': 'सीधा खरीदार बाज़ार',
    'landing.feature4Desc': 'अपनी उपज को सूचीबद्ध करें और सत्यापित खरीदारों के साथ जुड़ें। बिचौलियों के बिना सीधे बेचें और उचित मूल्य प्राप्त करें।',
    'landing.howItWorksTitle': 'सरल। स्मार्ट। लाभदायक।',
    'landing.howItWorksDesc': 'सिर्फ 3 आसान चरणों में बेहतर कृषि निर्णय लेना शुरू करें',
    'landing.step1Title': 'खेत का विवरण दर्ज करें',
    'landing.step1Desc': 'हमें अपनी भूमि के आकार, मिट्टी के प्रकार, स्थान और आप क्या उगाना चाहते हैं, इसके बारे में बताएं। 2 मिनट से भी कम समय लगता है।',
    'landing.step2Title': 'AI डेटा का विश्लेषण करता है',
    'landing.step2Desc': 'हमारा AI आपके लिए सर्वोत्तम अवसर खोजने के लिए मौसम के पैटर्न, बाजार की कीमतों, मिट्टी की स्थिति और मांग का अध्ययन करता है।',
    'landing.step3Title': 'परिणाम प्राप्त करें और जुड़ें',
    'landing.step3Desc': 'फसल की सिफारिशें, मूल्य भविष्यवाणी प्राप्त करें और खरीदारों से जुड़ें जो आपकी उपज को उचित मूल्य पर खरीदने के लिए तैयार हैं।',
    'landing.startJourney': 'अपनी यात्रा शुरू करें',
    'landing.previewTitle': 'KrishiSetu-AI को क्रिया में देखें',
    'landing.previewDesc': 'आधुनिक किसानों और स्मार्ट खुदरा विक्रेताओं के लिए डिज़ाइन किया गया एक संपूर्ण मंच',
    'landing.farmerDashboard': 'किसान डैशबोर्ड',
    'landing.cropRecs': 'फसल सिफारिशें',
    'landing.basedOnSoil': 'आपकी मिट्टी और बाजार के आधार पर',
    'landing.buyerDashboard': 'खरीदार डैशबोर्ड',
    'landing.availableProduce': 'उपलब्ध उपज',
    'landing.fromVerified': 'सत्यापित किसानों से',
    'landing.realTimeMarket': 'रियल-टाइम',
    'landing.marketData': 'बाजार डेटा',
    'landing.aiRecsLarge': 'AI-संचालित',
    'landing.aiRecsDesc': 'सिफारिशें',
    'landing.directAccessLarge': 'सीधी',
    'landing.directAccessDesc': 'खरीदार पहुँच',
    'landing.supportLarge': '24/7',
    'landing.supportDesc': 'सहायता',
    'landing.impactTitle': 'वास्तविक प्रभाव। वास्तविक परिणाम।',
    'landing.impactDesc': 'प्रौद्योगिकी के माध्यम से कृषि को बदलना और कृषि समुदायों को सशक्त बनाना',
    'landing.incomeIncrease': 'औसत आय वृद्धि',
    'landing.lossReduction': 'फसल नुकसान में कमी',
    'landing.transparentPricing': 'पारदर्शी मूल्य निर्धारण',
    'landing.noMiddlemen': 'बिचौलियों की आवश्यकता नहीं',
    'landing.verifiedFarmersTitle': 'सत्यापित किसान',
    'landing.verifiedFarmersDesc': 'खरीदारों के लिए गुणवत्ता और प्रामाणिकता सुनिश्चित करने के लिए सभी किसानों को सत्यापित किया जाता है',
    'landing.secureTransTitle': 'सुरक्षित लेनदेन',
    'landing.secureTransDesc': 'खरीदार संरक्षण के साथ सुरक्षित भुगतान प्रसंस्करण',
    'landing.expertSupportTitle': 'विशेषज्ञ सहायता',
    'landing.expertSupportDesc': 'आपको सफल होने में मदद करने के लिए कृषि विशेषज्ञ उपलब्ध हैं',
    'landing.readyToTransform': 'क्या आप अपनी खेती को बदलने के लिए तैयार हैं?',
    'landing.ctaDesc': 'उन हजारों किसानों से जुड़ें जो पहले से ही अधिक कमा रहे हैं, नुकसान कम कर रहे हैं और खरीदारों से सीधे जुड़ रहे हैं। आज ही होशियार, अधिक लाभदायक खेती की अपनी यात्रा शुरू करें।',
    'landing.scheduleDemo': 'डेमो शेड्यूल करें',
    'landing.setupTime': '2 मिनट में सेटअप',
    'landing.footerDesc': 'किसानों को AI-संचालित अंतर्दृष्टि के साथ सशक्त बनाना और उन्हें सीधे बाजारों से जोड़ना। कृषि के लिए एक स्मार्ट, अधिक लाभदायक भविष्य का निर्माण।',
    'landing.builtFor': 'नेशनल हैकाथॉन 2024 के लिए निर्मित',
    'landing.quickLinks': 'त्वरित लिंक',
    'landing.privacyPolicy': 'गोपनीयता नीति',
    'landing.termsOfService': 'सेवा की शर्तें',
    'landing.support': 'सहायता',
    'landing.allRightsReserved': 'सर्वाधिकार सुरक्षित।',

    
    // Crop Recommendation
    'cropRecommendation.title': 'फसल सिफारिश',
    'cropRecommendation.subtitle': 'अपने स्थान, मिट्टी के प्रकार और कृषि स्थितियों के आधार पर AI-संचालित फसल सिफारिशें प्राप्त करें।',
    'cropRecommendation.getRecommendations': 'फसल सिफारिशें प्राप्त करें',
    'cropRecommendation.newRecommendation': 'नई सिफारिश प्राप्त करें',
    'cropRecommendation.locationInfo': 'स्थान की जानकारी',
    'cropRecommendation.useCurrentLocation': 'वर्तमान स्थान का उपयोग करें',
    'cropRecommendation.enterManually': 'मैन्युअल रूप से दर्ज करें',
    'cropRecommendation.getCurrentLocation': 'वर्तमान स्थान प्राप्त करें',
    'cropRecommendation.gettingLocation': 'स्थान प्राप्त कर रहे हैं...',
    'cropRecommendation.farmDetails': 'खेत का विवरण',
    'cropRecommendation.soilType': 'मिट्टी का प्रकार',
    'cropRecommendation.selectSoilType': 'मिट्टी का प्रकार चुनें',
    'cropRecommendation.season': 'मौसम',
    'cropRecommendation.selectSeason': 'मौसम चुनें',
    'cropRecommendation.farmSize': 'खेत का आकार (एकड़)',
    'cropRecommendation.enterFarmSize': 'खेत का आकार दर्ज करें',
    'cropRecommendation.budget': 'बजट (₹)',
    'cropRecommendation.enterBudget': 'बजट दर्ज करें',
    'cropRecommendation.waterAvailability': 'पानी की उपलब्धता',
    'cropRecommendation.selectWaterAvailability': 'पानी की उपलब्धता चुनें',
    'cropRecommendation.farmingExperience': 'कृषि अनुभव',
    'cropRecommendation.selectExperience': 'अनुभव स्तर चुनें',
    'cropRecommendation.previousCrops': 'पिछली फसलें (सभी लागू का चयन करें)',
    'cropRecommendation.gettingRecommendations': 'सिफारिशें प्राप्त कर रहे हैं...',
    'cropRecommendation.recommendedCrops': 'अनुशंसित फसलें',
    'cropRecommendation.suitability': 'उपयुक्तता',
    'cropRecommendation.expectedYield': 'अपेक्षित उत्पादन',
    'cropRecommendation.whySuitable': 'यह फसल क्यों उपयुक्त है:',
    'cropRecommendation.bestCropToGrow': 'उगाने के लिए सबसे अच्छी फसल',
    'cropRecommendation.topRecommendation': 'आपके खेत के लिए हमारी शीर्ष सिफारिश',
    'cropRecommendation.saveResults': 'परिणाम सहेजें',
    'cropRecommendation.demoModeActive': 'डेमो मोड सक्रिय',
    'cropRecommendation.errorGettingRecommendations': 'सिफारिशें प्राप्त करने में त्रुटि',
    
    // Risk Levels
    'risk.low': 'कम जोखिम',
    'risk.medium': 'मध्यम जोखिम',
    'risk.high': 'उच्च जोखिम',
    
    // Languages
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.marathi': 'मराठी (Marathi)',
    
    // Common
    'common.save': 'सेव करें',
    'common.cancel': 'रद्द करें',
    'common.loading': 'लोड हो रहा है...',
    'common.state': 'राज्य',
    'common.district': 'जिला',
    'common.location': 'स्थान',
    'common.coordinates': 'निर्देशांक',
    
    // Placeholders
    'placeholder.state': 'राज्य',
    'placeholder.district': 'जिला',
    'placeholder.enterName': 'अपना नाम दर्ज करें',
    'placeholder.enterEmail': 'अपना ईमेल दर्ज करें',
    'placeholder.enterPassword': 'अपना पासवर्ड दर्ज करें',
    'placeholder.confirmPassword': 'अपने पासवर्ड की पुष्टि करें',
    'placeholder.regionExample': 'उदा., पंजाब, भारत',
    
    // Weather Advice
    'weather.title': 'मौसम और कृषि सलाह',
    'weather.subtitle': 'अपने स्थान के लिए AI-संचालित मौसम पूर्वानुमान और कार्यात्मक कृषि सुझाव प्राप्त करें।',
    'weather.getAdvice': 'मौसम सलाह प्राप्त करें',
    'weather.newSearch': 'नई खोज',
    'weather.currentWeather': 'वर्तमान मौसम',
    'weather.forecast': '3-दिन का पूर्वानुमान',
    'weather.warnings': 'मौसम चेतावनी',
    'weather.suitableActivities': 'उपयुक्त गतिविधियां',
    'weather.recommendedCrops': 'अनुशंसित फसलें',
    'weather.irrigationAdvice': 'सिंचाई सलाह',
    'weather.pestControl': 'कीट नियंत्रण',
    'weather.farmingRecommendations': 'कृषि सिफारिशें',
    'weather.useCurrentLocation': 'वर्तमान स्थान का उपयोग करें',
    'weather.enterCityName': 'शहर का नाम दर्ज करें',
    'weather.getCurrentLocation': 'वर्तमान स्थान प्राप्त करें',
    'weather.gettingLocation': 'स्थान प्राप्त कर रहे हैं...',
    'weather.cityName': 'शहर का नाम',
    'weather.enterCity': 'शहर का नाम दर्ज करें (जैसे, मुंबई, दिल्ली, पुणे)',
    'weather.gettingWeatherAdvice': 'मौसम सलाह प्राप्त कर रहे हैं...',
    'weather.temperature': 'तापमान',
    'weather.humidity': 'आर्द्रता',
    'weather.windSpeed': 'हवा की गति',
    'weather.visibility': 'दृश्यता',
    'weather.pressure': 'दबाव',
    'weather.uvIndex': 'UV सूचकांक',
    'weather.condition': 'स्थिति',
    'weather.feelsLike': 'महसूस होता है',
    'weather.today': 'आज',
    'weather.tomorrow': 'कल',
    'weather.dayAfter': 'परसों',
    'weather.highLow': 'उच्च/निम्न',
    'weather.rain': 'बारिश',
    'weather.needed': 'आवश्यक',
    'weather.amount': 'मात्रा',
    'weather.timing': 'समय',
    'weather.method': 'विधि',
    'weather.riskLevel': 'जोखिम स्तर',
    'weather.recommendations': 'सिफारिशें',
    'weather.priority': 'प्राथमिकता',
    'weather.high': 'उच्च',
    'weather.medium': 'मध्यम',
    'weather.low': 'निम्न',
    'weather.yes': 'हां',
    'weather.no': 'नहीं',
    'weather.errorGettingAdvice': 'मौसम सलाह प्राप्त करने में त्रुटि',
    'weather.adviceIncludes': 'मौसम सलाह में शामिल है: वर्तमान स्थितियां, 3-दिन का पूर्वानुमान, कृषि सिफारिशें, सिंचाई सलाह, कीट नियंत्रण सुझाव, और उपयुक्त गतिविधियां।',

    // Government Schemes
    'schemes.title': 'किसानों के लिए सरकारी योजनाएं',
    'schemes.subtitle': 'महाराष्ट्र के किसानों के लिए उपलब्ध विभिन्न सरकारी योजनाओं को खोजें और आवेदन करें',
    'schemes.searchPlaceholder': 'योजनाएं खोजें...',
    'schemes.filterByCategory': 'श्रेणी के अनुसार छानें',
    'schemes.allSchemes': 'सभी योजनाएं',
    'schemes.loanWaiver': 'कर्ज माफी',
    'schemes.subsidy': 'सब्सिडी',
    'schemes.insurance': 'बीमा',
    'schemes.directBenefit': 'प्रत्यक्ष लाभ',
    'schemes.infrastructure': 'बुनियादी ढांचा',
    'schemes.noSchemesFound': 'आपके मानदंडों से मेल खाने वाली कोई योजना नहीं मिली',
    'schemes.keyBenefits': 'मुख्य लाभ',
    'schemes.eligibilityCriteria': 'पात्रता मानदंड',
    'schemes.howToApply': 'आवेदन कैसे करें',
    'schemes.budgetAllocation': 'बजट आवंटन',
    'schemes.targetBeneficiaries': 'लक्षित लाभार्थी',
    'schemes.officialWebsite': 'आधिकारिक वेबसाइट',
    'schemes.visit': 'देखें',
    'schemes.learnMore': 'अधिक जानें और आवेदन करें',

    // Specific Schemes (Examples)
    'schemes.item1.name': 'पुण्यश्लोक अहिल्यादेवी होलकर शेतकरी कर्जमाफी योजना',
    'schemes.item1.desc': 'बकाया देनदारी वाले किसानों के लिए फसल ऋण माफी योजना',
    'schemes.item2.name': 'मुख्यमंत्री बलिराजा विजय योजना',
    'schemes.item2.desc': 'कृषि पंपों के लिए मुफ्त बिजली',
    'schemes.item3.name': 'कपास और सोयाबीन किसान सहायता योजना',
    'schemes.item3.desc': 'कपास और सोयाबीन किसानों के लिए वित्तीय सहायता',
    'schemes.item4.name': 'गोपीनाथ मुंडे किसान कल्याण योजना',
    'schemes.item4.desc': 'संकटग्रस्त किसानों के लिए आपातकालीन वित्तीय सहायता',
    'schemes.item5.name': 'किसान दुर्घटना बीमा योजना',
    'schemes.item5.desc': 'किसानों और खेतिहर मजदूरों के लिए दुर्घटना बीमा कवर',
    'schemes.item6.name': 'मराठवाड़ा वाटर ग्रिड परियोजना',
    'schemes.item6.desc': 'जल प्रबंधन और सिंचाई बुनियादी ढांचे का विकास',
    'schemes.item7.name': 'प्रधानमंत्री फसल बीमा योजना',
    'schemes.item7.desc': 'फसल नुकसान से सुरक्षा के लिए फसल बीमा योजना',
    'schemes.item8.name': 'मृदा स्वास्थ्य कार्ड योजना',
    'schemes.item8.desc': 'मुफ्त मिट्टी परीक्षण और पोषण प्रबंधन मार्गदर्शन',

    // Price Prediction
    'price.title': 'फसल मूल्य पूर्वानुमान',
    'price.subtitle': 'हमारे AI-संचालित मॉडल का उपयोग करके क्षेत्र और तिथि के आधार पर फसल की कीमत का पूर्वानुमान लगाएं।',
    'price.analyzerTitle': 'मूल्य पूर्वानुमान विश्लेषक',
    'price.selectCrop': 'फसल चुनें',
    'price.selectMandi': 'मंडी चुनें',
    'price.predictPrices': 'कीमतों का पूर्वानुमान लगाएं',
    'price.loading': 'पूर्वानुमान लोड हो रहे हैं...',
    'price.error': 'पूर्वानुमान प्राप्त करने में त्रुटि',
    'price.fourDayForecast': '4-दिवसीय मूल्य पूर्वानुमान',
    'price.dayX': 'दिन {day}',
    'price.predictedPriceQuintal': 'पूर्वानुमानित मूल्य (₹/क्विंटल)',
    'price.topMarketFactors': 'शीर्ष बाजार कारक',
    'price.aiConfidence': 'AI विश्वास',
    'price.historicalBaseline': '{crop} के लिए ऐतिहासिक आधार मूल्य निर्धारण',
    'price.regionalVariations': '{mandi} मंडी के लिए क्षेत्रीय विविधताएं',
    'price.seasonalSupply': 'मानक मौसमी आपूर्ति पैटर्न',
    'price.trendDisclaimer': 'ऐतिहासिक मंडी मूल्य रुझानों (2020–2025) पर आधारित। उपलब्ध लाइव डेटा पर मॉडल गतिशील रूप से अपडेट होते हैं।',
    'price.historical': 'ऐतिहासिक',
    'price.predicted': 'पूर्वानुमानित',
    'price.chartTitle': 'ऐतिहासिक बनाम AI-पूर्वानुमानित कीमतें (₹/क्विंटल)',
    'price.today': 'आज',

    // Disease Detection
    'disease.title': 'रोग पहचान',
    'disease.subtitle': 'फसल के रोगों की जल्दी पहचान करें और अपनी फसल की रक्षा के लिए उपचार सिफारिशें प्राप्त करें।',
    'disease.error': 'रोग का पता लगाने में त्रुटि',
    'disease.failedToConnect': 'पूर्वानुमान सर्वर से कनेक्ट करने में विफल।',
    'disease.uploadTitle': 'पौधे की छवि अपलोड करें',
    'disease.clickToUpload': 'अपलोड करने के लिए क्लिक करें या ड्रैग एंड ड्रॉप करें',
    'disease.imageFormats': 'PNG, JPG, GIF 10MB तक',
    'disease.clickToChange': 'छवि बदलने के लिए यहां क्लिक करें',
    'disease.alertUpload': 'कृपया रोग की पहचान के लिए पौधे की छवि अपलोड करें',
    'disease.analyzing': 'विश्लेषण किया जा रहा है...',
    'disease.detectButton': 'रोग का पता लगाएं',
    'disease.confidenceLevel': 'विश्वास स्तर',
    'disease.symptomsTitle': 'देखने के लिए लक्षण',
    'disease.treatmentTitle': 'उपचार सिफारिशें',
    'disease.preventionTitle': 'रोकथाम के उपाय',
    'disease.analyzeAnother': 'एक और पौधे का विश्लेषण करें',
    'disease.saveReport': 'रिपोर्ट सुरक्षित करें',
    'disease.detectedOnPlant': 'पौधे पर पता चला: {plant}',
    'disease.label': 'लेबल: {label}',
    
    // Default/Fallback strings
    'disease.diagVisual': 'दृश्य विश्लेषण के आधार पर निदान',
    'disease.checkSurround': 'समान संकेतों के लिए आसपास के पौधों की जाँच करें',
    'disease.consultExpert': 'एक कृषि विशेषज्ञ से परामर्श करें',
    'disease.reviewTreatments': 'इस रोग के लिए विशिष्ट कवकनाशी या उपचारों की समीक्षा करें',
    'disease.ensureRotation': 'फसल चक्र और उचित दूरी सुनिश्चित करें',
    'disease.avoidOverhead': 'यदि संभव हो तो ओवरहेड सिंचाई से बचें',
    
    'disease.healthy.name': 'स्वस्थ',
    'disease.healthy.symptom1': 'रोग का कोई दृश्य लक्षण नहीं',
    'disease.healthy.symptom2': 'पौधा स्वस्थ और जीवंत दिखाई देता है',
    'disease.healthy.treatment1': 'किसी उपचार की आवश्यकता नहीं है',
    'disease.healthy.treatment2': 'नियमित देखभाल और निगरानी जारी रखें',
    'disease.healthy.prevention1': 'उचित पानी का कार्यक्रम बनाए रखें',
    'disease.healthy.prevention2': 'पर्याप्त धूप और पोषक तत्व सुनिश्चित करें',
  },
  mr: {
    // Navigation & Sidebar
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.pricePrediction': 'किंमत अंदाज',
    'nav.cropRecommendation': 'पीक शिफारस',
    'nav.weatherAdvice': 'हवामान सल्ला',
    'nav.marketplace': 'बाजारपेठ',
    'nav.produceListings': 'उत्पादन यादी',
    'nav.community': 'समुदाय',
    'nav.orders': 'ऑर्डर',
    'nav.profile': 'प्रोफाइल',
    'nav.settings': 'सेटिंग्ज',
    'nav.diseaseDetection': 'रोग ओळख',
    'nav.governmentSchemes': 'सरकारी योजना',
    'nav.profileSettings': 'प्रोफाइल आणि सेटिंग्ज',
    'nav.sectionAiTools': 'AI साधने',
    'nav.sectionPlatform': 'प्लॅटफॉर्म',
    'nav.sectionAccount': 'खाते',
    
    // Dashboard Details
    'dashboard.welcomeMsg': 'कृषिसेतु AI मध्ये आपले स्वागत आहे.',
    'dashboard.greetingMorning': 'शुभ प्रभात',
    'dashboard.greetingAfternoon': 'नमस्कार',
    'dashboard.greetingEvening': 'शुभ संध्या',
    'dashboard.assistantDesc': 'महाराष्ट्रासाठी तुमचा AI-संचालित शेती सहाय्यक. पिकांच्या किमतीचा अंदाज मिळवा, रोग ओळखा, सरकारी योजना शोधा आणि खरेदीदारांशी कनेक्ट व्हा — सर्व एकाच ठिकाणी.',
    'dashboard.predictCropPrices': 'पिकांच्या किमतींचा अंदाज लावा',
    'dashboard.checkDisease': 'रोग तपासा',
    'dashboard.diseaseDetection': 'रोग ओळख',
    'dashboard.diseaseDetectionDesc': 'तुमच्या पिकाचा फोटो अपलोड करा — त्वरित रोग निदान + AI उपचार योजना मिळवा.',
    'dashboard.governmentSchemes': 'सरकारी योजना',
    'dashboard.governmentSchemesDesc': 'महाराष्ट्रातील शेतकऱ्यांसाठी कर्जमाफी, सबसिडी आणि विमा योजना ब्राउझ करा.',
    'dashboard.buyerMarketplace': 'खरेदीदार बाजारपेठ',
    'dashboard.buyerMarketplaceDesc': 'नकाशावर संपूर्ण महाराष्ट्रातील सत्यापित खरेदीदार आणि किरकोळ विक्रेत्यांशी कनेक्ट व्हा.',
    'dashboard.communityHub': 'समुदाय केंद्र',
    'dashboard.communityHubDesc': 'शेतकऱ्यांशी गप्पा मारा, माहिती सामायिक करा आणि एकत्र वाढा.',
    'dashboard.myOrders': 'माझे ऑर्डर',
    'dashboard.myOrdersDesc': 'तुमचे सक्रिय ऑर्डर्स ट्रॅक करा आणि डिलिव्हरी व्यवस्थापित करा.',
    'dashboard.allFeatures': 'सर्व वैशिष्ट्ये',
    'dashboard.modulesAvailable': '8 मॉड्यूल उपलब्ध',
    'dashboard.open': 'उघडा',
    'dashboard.farmingTips': 'शेती टिप्स आणि स्मरणपत्रे',
    'dashboard.quickAccess': 'त्वरित प्रवेश',
    
    // Stats
    'stat.cropsSupported': 'समर्थित पिके',
    'stat.cropsSub': 'कांदा, गहू, तांदूळ, टोमॅटो, बटाटा',
    'stat.govtSchemes': 'सरकारी योजना',
    'stat.schemesSub': 'सक्रिय योजना उपलब्ध',
    'stat.maharashtraMandis': 'महाराष्ट्रातील मंड्या',
    'stat.mandisSub': 'बाजारपेठा ट्रॅक केल्या',
    'stat.aiModels': 'AI मॉडेल्स',
    'stat.modelsSub': 'किंमत, रोग आणि हवामान',
    
    // Tips
    'tip.1': 'खरीप हंगाम जून-जुलै मध्ये सुरू होतो. पाण्याचे नियोजन लवकर सुरू करा.',
    'tip.2': 'रोग पसरण्यापूर्वी ते शोधण्यासाठी पिकांचे फोटो नियमितपणे अपलोड करा.',
    'tip.3': 'मंडीत तुमचे उत्पादन विकण्यापूर्वी 4-दिवसांचा किमतीचा अंदाज तपासा.',
    'tip.4': 'प्रधानमंत्री पीक विमा योजना अंतिम मुदत — पेरणीपूर्वी नोंदणी करा.',
    
    // Badges & Labels
    'badge.aiPowered': 'AI चालित',
    'badge.smart': 'स्मार्ट',
    'badge.live': 'थेट',
    'badge.geminiAi': 'Gemini AI',
    'badge.activeSchemes': '8 सक्रिय योजना',
    'badge.liveMap': 'थेट नकाशा',
    'badge.communities': '{count} समुदाय',
    'badge.track': 'ट्रॅक करा',
    'label.produceListings': 'उत्पादन यादी',
    'label.communityHub': 'समुदाय केंद्र',
    'label.profileSettings': 'प्रोफाइल सेटिंग्स',
    'label.appSettings': 'अँप सेटिंग्स',
    
    // Marketplace
    'marketplace.title': 'खरेदीदार नेटवर्क',
    'marketplace.subtitle': 'नकाशावर थेट आपल्या उत्पादनासाठी सत्यापित घाऊक खरेदीदार आणि निर्यातदार शोधा.',
    'marketplace.tabMap': 'खरेदीदार नकाशा',
    'marketplace.tabLive': 'थेट बाजार आणि खरेदीदार',
    'marketplace.sellingCrop': 'पीक विकणे:',
    'marketplace.wheat': 'गहू (शरबती)',
    'marketplace.rice': 'तांदूळ',
    'marketplace.onion': 'कांदा',
    'marketplace.tomato': 'टोमॅटो',
    'marketplace.potato': 'बटाटा',
    'marketplace.nearbyRetailers': 'जवळपासचे किरकोळ विक्रेते',
    'marketplace.sortShortest': 'सर्वात लहान...',
    'marketplace.sortProfit': 'सर्वात जास्त नफा',
    'marketplace.sortRating': 'सर्वोत्कृष्ट रेटिंग',
    'marketplace.loadingBuyers': 'खरेदीदार लोड होत आहेत...',
    'marketplace.noBuyers': 'खरेदीदार आढळले नाहीत',
    'marketplace.aiRecommended': 'AI शिफारस केलेले',
    'marketplace.offeredPrice': 'सवलत किंमत',
    'marketplace.transport': 'वाहतूक',
    'marketplace.netProfit': 'निव्वळ नफा',
    'marketplace.getDirections': 'दिशानिर्देश मिळवा',
    
    // Produce Listings
    'produceListings.title': 'उत्पादन यादी',
    'produceListings.subtitle': 'तुमच्या क्षेत्रातील शेतकऱ्यांकडून उपलब्ध उत्पादने ब्राउझ करा',
    'produceListings.listProduce': 'तुमचे उत्पादन सूचीबद्ध करा',
    'produceListings.loadingListings': 'याद्या लोड होत आहेत...',
    'produceListings.noListings': 'अद्याप कोणतीही उत्पादन यादी नाही',
    'produceListings.createFirst': 'पहिली यादी तयार करा',
    'produceListings.pricePer': 'प्रति {unit} किंमत',
    'produceListings.availableQty': 'उपलब्ध प्रमाण',
    'produceListings.totalValue': 'एकूण मूल्य',
    'produceListings.contactSeller': 'विक्रेत्याशी संपर्क साधा',
    
    // Community
    'community.title': 'समुदाय केंद्र',
    'community.subtitle': 'सहकारी शेतकऱ्यांशी कनेक्ट व्हा, ज्ञान सामायिक करा आणि एकत्र वाढा. खालील समुदाय एक्सप्लोर करा किंवा सामग्री शोधा.',
    'community.loading': 'समुदाय लोड होत आहेत...',
    'community.notFound': 'समुदाय आढळले नाहीत',
    'community.officialHub': 'अधिकृत केंद्र',
    'community.posts': '{count} पोस्ट',
    'community.justNow': 'नुकतेच',
    'community.loadingDetail': 'समुदाय लोड होत आहे...',
    'community.notFoundDetail': 'समुदाय आढळला नाही',
    'community.createPost': 'नोंद तयार करा',
    'community.subscribe': 'सदस्यता घ्या',
    'community.beFirst': '{name} समुदायाला हॅलो म्हणणारे पहिले व्हा!',
    'community.anonymous': 'अनामित वापरकर्ता',
    'community.messagePlaceholder': 'समुदायाला संदेश द्या...',
    'community.loginToJoin': 'संभाषणात सामील होण्यासाठी लॉग इन करा',
    'community.sendFailed': 'संदेश पाठविण्यास अयशस्वी.',
    'community.about': '{name} बद्दल',
    'community.created': '{date} रोजी तयार केले',
    'community.public': 'सार्वजनिक',
    'community.addGuide': 'एक समुदाय मार्गदर्शक जोडा',
    'community.moderators': 'नियंत्रक',
    'community.messageMods': 'नियंत्रकांना संदेश',
    
    // Orders
    'orders.title': 'शेतकरी ऑर्डर डॅशबोर्ड',
    'orders.subtitle': '{count} ऑर्डरमध्ये आपले येणारे उत्पादन शिपमेंट व्यवस्थापित करा.',
    'orders.listProduce': 'तुमचे उत्पादन सूचीबद्ध करा',
    'orders.loading': 'ऑर्डर लोड होत आहेत...',
    'orders.noOrders': 'अद्याप कोणत्याही ऑर्डर नाहीत',
    'orders.listFirst': 'तुमचे पहिले उत्पादन सूचीबद्ध करा',
    'orders.statusDelivered': 'वितरित केले',
    'orders.statusTransit': 'वाटेवर आहे',
    'orders.statusOrdered': 'ऑर्डर दिली',
    'orders.orderNumber': 'ऑर्डर #{id}',
    'orders.placedOn': '{date} रोजी ठेवले',
    'orders.buyer': 'खरेदीदार: {name}',
    'orders.quantityLabel': 'प्रमाण',
    'orders.payoutLabel': 'एकूण पेआउट',
    
    // Profile
    'profile.title': 'प्रोफाइल',
    'profile.subtitle': 'तुमची सार्वजनिक प्रोफाइल माहिती पहा आणि व्यवस्थापित करा.',
    'profile.loading': 'प्रोफाइल लोड होत आहे...',
    'profile.pleaseLogin': 'कृपया तुमची प्रोफाइल पाहण्यासाठी लॉग इन करा',
    'profile.recently': 'नुकतेच',
    'profile.joined': 'सामील झाले {date}',
    'profile.editProfile': 'प्रोफाइल संपादित करा',
    'profile.fullName': 'पूर्ण नाव',
    'profile.fullNamePlaceholder': 'तुमचे पूर्ण नाव',
    'profile.locationLabel': 'स्थान',
    'profile.locationPlaceholder': 'उदा. नाशिक, महाराष्ट्र',
    'profile.bioLabel': 'माहिती',
    'profile.bioPlaceholder': 'इतरांना आपल्याबद्दल सांगा...',
    'profile.avatarLabel': 'अवतार URL',
    'profile.saving': 'जतन करत आहे...',
    'profile.saveChanges': 'बदल जतन करा',
    'profile.saveFailed': 'प्रोफाइल जतन करण्यात अयशस्वी',
    'profile.statsOrders': 'ऑर्डर्स',
    'profile.statsListings': 'याद्या',
    'profile.statsCommunities': 'समुदाय',
    'profile.statsPosts': 'पोस्ट',
    'profile.recentActivity': 'अलीकडील क्रियाकलाप',
    'profile.noActivity': 'अद्याप कोणताही अलीकडील क्रियाकलाप नाही.',
    'profile.activityDelivered': 'वितरित केले {product}',
    'profile.activityOrdered': 'ऑर्डर केले {product}',
    'profile.activityUnits': '{quantity} युनिट्स',
    'profile.activityPosted': 'पोस्ट केले: {title}',
    'profile.activityCommPost': 'समुदाय पोस्ट',
    'profile.activityListed': 'सूचीबद्ध केले {crop}',
    'profile.activityListedDesc': '{quantity} युनिट्स ₹{price}/युनिट',
    
    // Settings
    'settings.title': 'सेटिंग्ज',
    'settings.subtitle': 'तुमच्या खाते सेटिंग्ज, प्रोफाइल आणि प्राधान्यांचे व्यवस्थापन करा.',
    'settings.profile': 'प्रोफाइल',
    'settings.appearance': 'दिसणे',
    'settings.notifications': 'सूचना',
    'settings.translation': 'भाषांतर',
    'settings.myOrders': 'माझे ऑर्डर',
    'settings.chooseLanguage': 'तुमची पसंतीची भाषा निवडा.',
    'settings.updateProfile': 'प्रोफाइल अपडेट करा',
    'settings.profileSectionDesc': 'असे इतर तुम्हाला साइटवर पाहतील.',
    'settings.profilePicture': 'प्रोफाइल चित्र',
    'settings.username': 'वापरकर्ता नाव',
    'settings.displayName': 'प्रदर्शन नाव',
    'settings.defaultRegion': 'डिफॉल्ट प्रदेश',
    'settings.account': 'खाते',
    'settings.accountDesc': 'तुमची खाते सुरक्षा आणि ओळख व्यवस्थापित करा.',
    'settings.userId': 'वापरकर्ता आयडी',
    'settings.userIdCopied': 'वापरकर्ता आयडी क्लिपबोर्डवर कॉपी झाला!',
    'settings.emailAddress': 'ईमेल पत्ता',
    'settings.emailDesc': 'तुमचा ईमेल पत्ता {email} आहे. हे बदलले जाऊ शकत नाही.',
    'settings.appearanceDesc': 'अर्जाचे स्वरूप आणि अनुभव सानुकूलित करा.',
    'settings.appearanceSoon': 'देखावा सेटिंग्ज लवकरच येत आहेत...',
    'settings.notificationsDesc': 'तुमची सूचना प्राधान्ये व्यवस्थापित करा.',
    'settings.notificationsSoon': 'सूचना सेटिंग्ज लवकरच येत आहेत...',
    'settings.ordersDesc': 'तुमचा ऑर्डर इतिहास पहा आणि व्यवस्थापित करा.',
    'settings.ordersSoon': 'ऑर्डर इतिहास लवकरच येत आहे...',
    'settings.note': 'टीप:',
    'settings.translationNote': 'भाषा बदल त्वरित लागू केले जातील. काही सामग्री पूर्णपणे अद्यतनित करण्यासाठी पृष्ठ रीफ्रेश करणे आवश्यक असू शकते.',
    
    // TopBar
    'topbar.logout': 'लॉग आउट',
    
    // Auth
    'auth.login': 'साइन इन',
    'auth.signup': 'साइन अप',
    'auth.welcomeBack': 'परत स्वागत',
    'auth.signInToAccount': 'तुमच्या खात्यात साइन इन करा',
    'auth.createAccount': 'खाते तयार करा',
    'auth.signUpToStart': 'सुरुवात करण्यासाठी साइन अप करा',
    'auth.email': 'ईमेल पत्ता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्डची पुष्टी करा',
    'auth.fullName': 'पूर्ण नाव',
    'auth.enterEmail': 'तुमचा ईमेल टाका',
    'auth.enterPassword': 'तुमचा पासवर्ड टाका',
    'auth.enterName': 'तुमचे नाव टाका',
    'auth.confirmYourPassword': 'तुमच्या पासवर्डची पुष्टी करा',
    'auth.signingIn': 'साइन इन करत आहे...',
    'auth.creatingAccount': 'खाते तयार करत आहे...',
    'auth.dontHaveAccount': 'खाते नाही?',
    'auth.alreadyHaveAccount': 'आधीच खाते आहे?',
    'auth.passwordsDoNotMatch': 'पासवर्ड जुळत नाहीत',
    'auth.passwordLengthError': 'पासवर्ड किमान ६ अक्षरांचा असावा',
    
    // Landing Page
    'landing.navFeatures': 'वैशिष्ट्ये',
    'landing.navHowItWorks': 'हे कसे कार्य करते',
    'landing.navBenefits': 'फायदे',
    'landing.navAbout': 'आमच्याबद्दल',
    'landing.signIn': 'साइन इन',
    'landing.getStarted': 'सुरुवात करा',
    'landing.heroBadge': '🌾 AI-आधारित कृषी बुद्धिमत्ता',
    'landing.heroTitle1': 'हुशारीने पिकवा,',
    'landing.heroTitle2': 'उत्तम कमवा',
    'landing.heroDesc': 'AI-चालित पीक शिफारसी, रिअल-टाइम बाजार भाव आणि खरेदीदारांशी थेट प्रवेशासह आपल्या शेतीला सक्षम करा. डेटा-आधारित निर्णय घ्या जे तुमचा नफा वाढवतील.',
    'landing.getStartedFree': 'विनामूल्य सुरुवात करा',
    'landing.watchDemo': 'डेमो पहा',
    'landing.noCreditCard': 'क्रेडिट कार्डची आवश्यकता नाही',
    'landing.freeForFarmers': 'शेतकऱ्यांसाठी मोफत',
    'landing.aiAnalysisComplete': 'AI विश्लेषण पूर्ण',
    'landing.projectedProfit': 'अपेक्षित नफा वाढ',
    'landing.marketPrice': 'बाजार भाव',
    'landing.weatherPerfect': 'उत्तम',
    'landing.whyChooseTitle': 'शेतकरी आणि किरकोळ विक्रेते आम्हाला का निवडतात',
    'landing.whyChooseDesc': 'वास्तविक उपाय जे उत्पन्न वाढवतात, जोखीम कमी करतात आणि शेतांना थेट बाजाराशी जोडतात',
    'landing.benefit1Title': 'शेतकऱ्यांसाठी जास्त नफा',
    'landing.benefit1Desc': 'योग्य वेळी विक्री करण्यासाठी रिअल-टाइम बाजार भाव आणि AI शिफारसी मिळवा. डेटा-चालित निर्णयांसह तुमचे उत्पन्न ३०% पर्यंत वाढवा.',
    'landing.benefit2Title': 'स्मार्ट पीक निर्णय',
    'landing.benefit2Desc': 'तुमच्या जमिनीसाठी सर्वात फायदेशीर पिकांची शिफारस करण्यासाठी AI तुमच्या मातीचा, हवामानाचा आणि बाजारातील मागणीचा अभ्यास करते. पीक अपयश कमी करा आणि उत्पादन वाढवा.',
    'landing.benefit3Title': 'थेट खरेदीदार कनेक्शन',
    'landing.benefit3Desc': 'मध्यस्थांना वगळा आणि थेट किरकोळ विक्रेते आणि खरेदीदारांना विक्री करा. पारदर्शक, वाजवी किंमतीसह तुमच्या खिशात अधिक नफा ठेवा.',
    'landing.benefit4Title': 'नुकसान आणि जोखीम कमी',
    'landing.benefit4Desc': 'हवामान इशारे, रोग अंदाज आणि बाजारपेठेतील अंतर्दृष्टी तुम्हाला नुकसान टाळण्यास मदत करतात. AI बुद्धिमत्तेद्वारे समर्थित माहितीपूर्ण निर्णय घ्या.',
    'landing.benefit5Title': 'किरकोळ विक्रेत्यांसाठी विश्वसनीय सोर्सिंग',
    'landing.benefit5Desc': 'खरेदीदारांना सत्यापित शेतकऱ्यांकडून दर्जेदार उत्पादनांमध्ये थेट प्रवेश मिळतो. दीर्घकालीन संबंध निर्माण करा आणि सातत्यपूर्ण पुरवठा सुनिश्चित करा.',
    'landing.benefit6Title': 'मध्यस्थांवर अवलंबित्व नाही',
    'landing.benefit6Desc': 'तुमच्या विक्री आणि किंमतीवर नियंत्रण ठेवा. खरेदीदारांशी थेट कनेक्ट व्हा आणि मध्यस्थांना मार्जिन न गमावता वाजवी व्यवहार निश्चित करा.',
    'landing.featuresTitle': 'शेतकऱ्यांसाठी तयार केलेली शक्तिशाली वैशिष्ट्ये',
    'landing.featuresDesc': 'बेहतर शेती निर्णय घेण्यासाठी आणि आपला व्यवसाय वाढवण्यासाठी आपल्याला आवश्यक असलेले सर्वकाही',
    'landing.feature1Title': 'AI पीक शिफारस',
    'landing.feature1Desc': 'तुमच्या मातीचा प्रकार, हवामान आणि बाजारातील मागणीनुसार वैयक्तिकृत पीक सूचना मिळवा. जे सर्वात चांगले विकले जाते तेच पिकवा.',
    'landing.feature2Title': 'बाजार भाव अंदाज',
    'landing.feature2Desc': 'भविष्यातील किमतीचे कल आणि वर्तमान बाजार दर पहा. जास्तीत जास्त नफ्यासाठी केव्हा विकायचे हे AI-चालित अंदाजांसह जाणून घ्या.',
    'landing.feature3Title': 'हवामान अंतर्दृष्टी',
    'landing.feature3Desc': 'रिअल-टाइम हवामान अपडेट्स आणि शेती सल्ला मिळवा. अचूक अंदाज आणि अलर्टसह आपल्या क्रियाकलापांचे नियोजन करा.',
    'landing.feature4Title': 'थेट खरेदीदार बाजारपेठ',
    'landing.feature4Desc': 'तुमचे उत्पादन सूचीबद्ध करा आणि सत्यापित खरेदीदारांशी कनेक्ट व्हा. मध्यस्थांशिवाय थेट विक्री करा आणि वाजवी भाव मिळवा.',
    'landing.howItWorksTitle': 'सोपे. स्मार्ट. फायदेशीर.',
    'landing.howItWorksDesc': 'फक्त ३ सोप्या टप्प्यात चांगले शेती निर्णय घेण्यास सुरुवात करा',
    'landing.step1Title': 'शेतीचे तपशील प्रविष्ट करा',
    'landing.step1Desc': 'आम्हाला तुमच्या जमिनीचा आकार, मातीचा प्रकार, स्थान आणि तुम्हाला काय पिकवायचे आहे याबद्दल सांगा. २ मिनिटांपेक्षा कमी वेळ लागतो.',
    'landing.step2Title': 'AI डेटाचे विश्लेषण करते',
    'landing.step2Desc': 'आमचा AI तुमच्यासाठी सर्वोत्तम संधी शोधण्यासाठी हवामानाचे स्वरूप, बाजार भाव, मातीची परिस्थिती आणि मागणीचा अभ्यास करतो.',
    'landing.step3Title': 'निकाल मिळवा आणि कनेक्ट व्हा',
    'landing.step3Desc': 'पीक शिफारसी, किंमत अंदाज मिळवा आणि खरेदीदारांशी कनेक्ट व्हा जे तुमचे उत्पादन वाजवी दरात खरेदी करण्यास तयार आहेत.',
    'landing.startJourney': 'तुमचा प्रवास सुरू करा',
    'landing.previewTitle': 'KrishiSetu-AI कृतीमध्ये पहा',
    'landing.previewDesc': 'आधुनिक शेतकरी आणि स्मार्ट किरकोळ विक्रेत्यांसाठी डिझाइन केलेले एक संपूर्ण प्लॅटफॉर्म',
    'landing.farmerDashboard': 'शेतकरी डॅशबोर्ड',
    'landing.cropRecs': 'पीक शिफारसी',
    'landing.basedOnSoil': 'तुमच्या माती आणि बाजारपेठेवर आधारित',
    'landing.buyerDashboard': 'खरेदीदार डॅशबोर्ड',
    'landing.availableProduce': 'उपलब्ध उत्पादन',
    'landing.fromVerified': 'सत्यापित शेतकऱ्यांकडून',
    'landing.realTimeMarket': 'रियल-टाइम',
    'landing.marketData': 'बाजार डेटा',
    'landing.aiRecsLarge': 'AI-चालित',
    'landing.aiRecsDesc': 'शिफारसी',
    'landing.directAccessLarge': 'थेट',
    'landing.directAccessDesc': 'खरेदीदार प्रवेश',
    'landing.supportLarge': '२४/७',
    'landing.supportDesc': 'पाठिंबा',
    'landing.impactTitle': 'वास्तविक प्रभाव. वास्तविक निकाल.',
    'landing.impactDesc': 'तंत्रज्ञानाद्वारे शेती बदलणे आणि शेती समुदायांना सक्षम करणे',
    'landing.incomeIncrease': 'सरासरी उत्पन्न वाढ',
    'landing.lossReduction': 'पीक नुकसानीत घट',
    'landing.transparentPricing': 'पारदर्शक किंमत',
    'landing.noMiddlemen': 'मध्यस्थांची गरज नाही',
    'landing.verifiedFarmersTitle': 'सत्यापित शेतकरी',
    'landing.verifiedFarmersDesc': 'खरेदीदारांसाठी गुणवत्ता आणि सत्यता सुनिश्चित करण्यासाठी सर्व शेतकऱ्यांची पडताळणी केली जाते',
    'landing.secureTransTitle': 'सुरक्षित व्यवहार',
    'landing.secureTransDesc': 'खरेदीदार संरक्षणासह सुरक्षित पेमेंट प्रक्रिया',
    'landing.expertSupportTitle': 'तज्ञ समर्थन',
    'landing.expertSupportDesc': 'आपल्याला यशस्वी होण्यास मदत करण्यासाठी कृषी तज्ञ उपलब्ध आहेत',
    'landing.readyToTransform': 'आपली शेती बदलण्यासाठी तयार आहात का?',
    'landing.ctaDesc': 'आधीच जास्त कमाई करणाऱ्या, नुकसान कमी करणाऱ्या आणि खरेदीदारांशी थेट जोडल्या जाणाऱ्या हजारो शेतकऱ्यांमध्ये सामील व्हा. आजच तुमचा स्मार्ट, अधिक फायदेशीर शेतीचा प्रवास सुरू करा.',
    'landing.scheduleDemo': 'डेमो शेड्युल करा',
    'landing.setupTime': '२ मिनिटांत सेटअप',
    'landing.footerDesc': 'शेतकऱ्यांना AI-चालित अंतर्दृष्टीसह सक्षम करणे आणि त्यांना थेट बाजारपेठेशी जोडणे. कृषी क्षेत्रासाठी स्मार्ट, अधिक फायदेशीर भविष्य घडवणे.',
    'landing.builtFor': 'नॅशनल हॅकाथॉन २०२४ साठी निर्मित',
    'landing.quickLinks': 'त्वरित लिंक',
    'landing.privacyPolicy': 'गोपनीयता धोरण',
    'landing.termsOfService': 'सेवेच्या अटी',
    'landing.support': 'आधार',
    'landing.allRightsReserved': 'सर्व हक्क राखीव.',

    
    // Crop Recommendation
    'cropRecommendation.title': 'पीक शिफारस',
    'cropRecommendation.subtitle': 'तुमच्या स्थान, मातीचा प्रकार आणि शेती परिस्थितीच्या आधारे AI-चालित पीक शिफारसी मिळवा.',
    'cropRecommendation.getRecommendations': 'पीक शिफारसी मिळवा',
    'cropRecommendation.newRecommendation': 'नवीन शिफारस मिळवा',
    'cropRecommendation.locationInfo': 'स्थान माहिती',
    'cropRecommendation.useCurrentLocation': 'सध्याचे स्थान वापरा',
    'cropRecommendation.enterManually': 'मॅन्युअली प्रविष्ट करा',
    'cropRecommendation.getCurrentLocation': 'सध्याचे स्थान मिळवा',
    'cropRecommendation.gettingLocation': 'स्थान मिळवत आहे...',
    'cropRecommendation.farmDetails': 'शेताचे तपशील',
    'cropRecommendation.soilType': 'मातीचा प्रकार',
    'cropRecommendation.selectSoilType': 'मातीचा प्रकार निवडा',
    'cropRecommendation.season': 'हंगाम',
    'cropRecommendation.selectSeason': 'हंगाम निवडा',
    'cropRecommendation.farmSize': 'शेताचा आकार (एकर)',
    'cropRecommendation.enterFarmSize': 'शेताचा आकार प्रविष्ट करा',
    'cropRecommendation.budget': 'बजेट (₹)',
    'cropRecommendation.enterBudget': 'बजेट प्रविष्ट करा',
    'cropRecommendation.waterAvailability': 'पाण्याची उपलब्धता',
    'cropRecommendation.selectWaterAvailability': 'पाण्याची उपलब्धता निवडा',
    'cropRecommendation.farmingExperience': 'शेती अनुभव',
    'cropRecommendation.selectExperience': 'अनुभव पातळी निवडा',
    'cropRecommendation.previousCrops': 'मागील पिके (सर्व लागू निवडा)',
    'cropRecommendation.gettingRecommendations': 'शिफारसी मिळवत आहे...',
    'cropRecommendation.recommendedCrops': 'शिफारस केलेली पिके',
    'cropRecommendation.suitability': 'योग्यता',
    'cropRecommendation.expectedYield': 'अपेक्षित उत्पादन',
    'cropRecommendation.whySuitable': 'हे पीक का योग्य आहे:',
    'cropRecommendation.bestCropToGrow': 'लावण्यासाठी सर्वोत्तम पीक',
    'cropRecommendation.topRecommendation': 'तुमच्या शेतासाठी आमची शीर्ष शिफारस',
    'cropRecommendation.saveResults': 'परिणाम सेव्ह करा',
    'cropRecommendation.demoModeActive': 'डेमो मोड सक्रिय',
    'cropRecommendation.errorGettingRecommendations': 'शिफारसी मिळवण्यात त्रुटी',
    
    // Risk Levels
    'risk.low': 'कमी जोखीम',
    'risk.medium': 'मध्यम जोखीम',
    'risk.high': 'उच्च जोखीम',
    
    // Languages
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.marathi': 'मराठी (Marathi)',
    
    // Common
    'common.save': 'सेव्ह करा',
    'common.cancel': 'रद्द करा',
    'common.loading': 'लोड होत आहे...',
    'common.state': 'राज्य',
    'common.district': 'जिल्हा',
    'common.location': 'स्थान',
    'common.coordinates': 'निर्देशांक',
    
    // Placeholders
    'placeholder.state': 'राज्य',
    'placeholder.district': 'जिल्हा',
    'placeholder.enterName': 'तुमचे नाव टाका',
    'placeholder.enterEmail': 'तुमचा ईमेल टाका',
    'placeholder.enterPassword': 'तुमचा पासवर्ड टाका',
    'placeholder.confirmPassword': 'तुमच्या पासवर्डची पुष्टी करा',
    'placeholder.regionExample': 'उदा., महाराष्ट्र, भारत',
    
    // Weather Advice
    'weather.title': 'हवामान आणि शेती सल्ला',
    'weather.subtitle': 'तुमच्या स्थानासाठी AI-चालित हवामान अंदाज आणि कार्यात्मक शेती टिप्स मिळवा।',
    'weather.getAdvice': 'हवामान सल्ला मिळवा',
    'weather.newSearch': 'नवीन शोध',
    'weather.currentWeather': 'सध्याचे हवामान',
    'weather.forecast': '3-दिवसांचा अंदाज',
    'weather.warnings': 'हवामान चेतावणी',
    'weather.suitableActivities': 'योग्य क्रियाकलाप',
    'weather.recommendedCrops': 'शिफारस केलेली पिके',
    'weather.irrigationAdvice': 'सिंचन सल्ला',
    'weather.pestControl': 'कीड नियंत्रण',
    'weather.farmingRecommendations': 'शेती शिफारसी',
    'weather.useCurrentLocation': 'सध्याचे स्थान वापरा',
    'weather.enterCityName': 'शहराचे नाव प्रविष्ट करा',
    'weather.getCurrentLocation': 'सध्याचे स्थान मिळवा',
    'weather.gettingLocation': 'स्थान मिळवत आहे...',
    'weather.cityName': 'शहराचे नाव',
    'weather.enterCity': 'शहराचे नाव प्रविष्ट करा (उदा., मुंबई, दिल्ली, पुणे)',
    'weather.gettingWeatherAdvice': 'हवामान सल्ला मिळवत आहे...',
    'weather.temperature': 'तापमान',
    'weather.humidity': 'आर्द्रता',
    'weather.windSpeed': 'वाऱ्याचा वेग',
    'weather.visibility': 'दृश्यता',
    'weather.pressure': 'दाब',
    'weather.uvIndex': 'UV निर्देशांक',
    'weather.condition': 'स्थिती',
    'weather.feelsLike': 'असे वाटते',
    'weather.today': 'आज',
    'weather.tomorrow': 'उद्या',
    'weather.dayAfter': 'परवा',
    'weather.highLow': 'उच्च/निम्न',
    'weather.rain': 'पाऊस',
    'weather.needed': 'आवश्यक',
    'weather.amount': 'प्रमाण',
    'weather.timing': 'वेळ',
    'weather.method': 'पद्धत',
    'weather.riskLevel': 'जोखीम पातळी',
    'weather.recommendations': 'शिफारसी',
    'weather.priority': 'प्राधान्य',
    'weather.high': 'उच्च',
    'weather.medium': 'मध्यम',
    'weather.low': 'निम्न',
    'weather.yes': 'होय',
    'weather.no': 'नाही',
    'weather.errorGettingAdvice': 'हवामान सल्ला मिळवण्यात त्रुटी',
    'weather.adviceIncludes': 'हवामानल्ल्यामध्ये समाविष्ट आहे: सध्याची स्थिती, 3-दिवसांचा अंदाज, शेती शिफारसी, सिंचन सल्ला, कीड नियंत्रण टिप्स आणि योग्य क्रियाकलाप।',

    // Government Schemes
    'schemes.title': 'शेतकऱ्यांसाठी सरकारी योजना',
    'schemes.subtitle': 'महाराष्ट्रातील शेतकऱ्यांसाठी उपलब्ध असलेल्या विविध सरकारी योजना पहा आणि अर्ज करा',
    'schemes.searchPlaceholder': 'योजना शोधा...',
    'schemes.filterByCategory': 'श्रेणीनुसार फिल्टर करा',
    'schemes.allSchemes': 'सर्व योजना',
    'schemes.loanWaiver': 'कर्जमाफी',
    'schemes.subsidy': 'सब्सिडी',
    'schemes.insurance': 'विमा',
    'schemes.directBenefit': 'प्रत्यक्ष लाभ',
    'schemes.infrastructure': 'पायाभूत सुविधा',
    'schemes.noSchemesFound': 'तुमच्या निकषांशी जुळणारी कोणतीही योजना सापडली नाही',
    'schemes.keyBenefits': 'मुख्य फायदे',
    'schemes.eligibilityCriteria': 'पात्रता निकष',
    'schemes.howToApply': 'अर्ज कसा करावा',
    'schemes.budgetAllocation': 'बजेट वाटप',
    'schemes.targetBeneficiaries': 'लक्षित लाभार्थी',
    'schemes.officialWebsite': 'अधिकृत वेबसाइट',
    'schemes.visit': 'भेट द्या',
    'schemes.learnMore': 'अधिक जाणून घ्या आणि अर्ज करा',

    // Specific Schemes (Examples)
    'schemes.item1.name': 'पुण्यश्लोक अहिल्यादेवी होळकर शेतकरी कर्जमाफी योजना',
    'schemes.item1.desc': 'थकीत येणे असलेल्या शेतकऱ्यांसाठी पीक कर्जमाफी योजना',
    'schemes.item2.name': 'मुख्यमंत्री बळीराजा विजय योजना',
    'schemes.item2.desc': 'कृषी पंपांसाठी मोफत वीज',
    'schemes.item3.name': 'कापूस आणि सोयाबीन शेतकरी सहाय्यता योजना',
    'schemes.item3.desc': 'कापूस आणि सोयाबीन शेतकऱ्यांसाठी आर्थिक मदत',
    'schemes.item4.name': 'गोपीनाथ मुंडे शेतकरी कल्याण योजना',
    'schemes.item4.desc': 'संकटग्रस्त शेतकऱ्यांसाठी आपत्कालीन आर्थिक मदत',
    'schemes.item5.name': 'शेतकरी अपघात विमा योजना',
    'schemes.item5.desc': 'शेतकरी आणि शेतमजुरांसाठी अपघात विमा संरक्षण',
    'schemes.item6.name': 'मराठवाडा वॉटर ग्रिड प्रकल्प',
    'schemes.item6.desc': 'जल व्यवस्थापन आणि सिंचन पायाभूत सुविधा विकास',
    'schemes.item7.name': 'प्रधानमंत्री फसल बीमा योजना',
    'schemes.item7.desc': 'पीक नुकसानीपासून संरक्षणासाठी पीक विमा योजना',
    'schemes.item8.name': 'मृदा आरोग्य कार्ड योजना',
    'schemes.item8.desc': 'मोफत माती परीक्षण आणि पोषण व्यवस्थापन मार्गदर्शन',

    // Price Prediction
    'price.title': 'पीक किंमत अंदाज',
    'price.subtitle': 'आमच्या AI-संचालित मॉडेलचा वापर करून प्रदेश आणि तारखेनुसार पिकाच्या किंमतीचा अंदाज लावा.',
    'price.analyzerTitle': 'किंमत अंदाज विश्लेषक',
    'price.selectCrop': 'पीक निवडा',
    'price.selectMandi': 'मंडी निवडा',
    'price.predictPrices': 'किमतींचा अंदाज लावा',
    'price.loading': 'अंदाज लोड होत आहेत...',
    'price.error': 'अंदाज मिळवण्यात त्रुटी',
    'price.fourDayForecast': '4-दिवसांचा किमतीचा अंदाज',
    'price.dayX': 'दिवस {day}',
    'price.predictedPriceQuintal': 'अपेक्षित किंमत (₹/क्विंटल)',
    'price.topMarketFactors': 'प्रमुख बाजार घटक',
    'price.aiConfidence': 'AI आत्मविश्वास',
    'price.historicalBaseline': '{crop} साठी ऐतिहासिक मूळ किंमत',
    'price.regionalVariations': '{mandi} मंडीसाठी प्रादेशिक तफावत',
    'price.seasonalSupply': 'मानक हंगामी पुरवठा नमुने',
    'price.trendDisclaimer': 'ऐतिहासिक मंडी किंमत कल (2020-2025) वर आधारित. उपलब्ध थेट डेटावर मॉडेल गतिशीलपणे अपडेट होतात.',
    'price.historical': 'ऐतिहासिक',
    'price.predicted': 'अपेक्षित',
    'price.chartTitle': 'ऐतिहासिक वि AI-अपेक्षित किमती (₹/क्विंटल)',
    'price.today': 'आज',

    // Disease Detection
    'disease.title': 'रोग ओळख',
    'disease.subtitle': 'पिकांवरील रोगांची लवकर ओळख करा आणि तुमच्या पिकाच्या संरक्षणासाठी उपचार शिफारसी मिळवा.',
    'disease.error': 'रोग ओळखण्यात त्रुटी',
    'disease.failedToConnect': 'अंदाज सर्व्हरशी कनेक्ट करण्यात अपयश.',
    'disease.uploadTitle': 'रोपाची प्रतिमा अपलोड करा',
    'disease.clickToUpload': 'अपलोड करण्यासाठी क्लिक करा किंवा ड्रॅग आणि ड्रॉप करा',
    'disease.imageFormats': 'PNG, JPG, GIF 10MB पर्यंत',
    'disease.clickToChange': 'प्रतिमा बदलण्यासाठी येथे क्लिक करा',
    'disease.alertUpload': 'कृपया रोग ओळखण्यासाठी रोपाची प्रतिमा अपलोड करा',
    'disease.analyzing': 'विश्लेषण सुरू आहे...',
    'disease.detectButton': 'रोग ओळखा',
    'disease.confidenceLevel': 'विश्वास पातळी',
    'disease.symptomsTitle': 'लक्षणे तपासा',
    'disease.treatmentTitle': 'उपचार शिफारसी',
    'disease.preventionTitle': 'प्रतिबंधात्मक उपाय',
    'disease.analyzeAnother': 'दुसऱ्या रोपाचे विश्लेषण करा',
    'disease.saveReport': 'अहवाल जतन करा',
    'disease.detectedOnPlant': 'रोपावर आढळले: {plant}',
    'disease.label': 'लेबल: {label}',
    
    // Default/Fallback strings
    'disease.diagVisual': 'दृश्य विश्लेषणावर आधारित निदान',
    'disease.checkSurround': 'समान लक्षणांसाठी सभोवतालच्या रोपांची तपासणी करा',
    'disease.consultExpert': 'कृषी तज्ज्ञांचा सल्ला घ्या',
    'disease.reviewTreatments': 'या रोगासाठी विशिष्ट बुरशीनाशके किंवा उपचारांचा आढावा घ्या',
    'disease.ensureRotation': 'पीक फेरपालट आणि योग्य अंतर सुनिश्चित करा',
    'disease.avoidOverhead': 'शक्य असल्यास ओव्हरहेड सिंचन टाळा',
    
    'disease.healthy.name': 'निरोगी',
    'disease.healthy.symptom1': 'रोगाची कोणतीही दृश्य लक्षणे नाहीत',
    'disease.healthy.symptom2': 'रोप निरोगी आणि टवटवीत दिसत आहे',
    'disease.healthy.treatment1': 'कोणत्याही उपचारांची गरज नाही',
    'disease.healthy.treatment2': 'नियमित काळजी आणि देखरेख सुरू ठेवा',
    'disease.healthy.prevention1': 'पाण्याचे योग्य वेळापत्रक ठेवा',
    'disease.healthy.prevention2': 'पुरेशी सूर्यप्रकाश आणि पोषक तत्वे सुनिश्चित करा',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('krishisetu-language')
    return (saved as Language) || 'en'
  })

  useEffect(() => {
    localStorage.setItem('krishisetu-language', language)
  }, [language])

  const t = (key: string): string => {
    const langTranslations = translations[language] as Record<string, string>
    return langTranslations[key] || key
  }

  const value = {
    language,
    setLanguage,
    t
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}